{{- if .Values.global.psp.enabled }}
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.cilium-agent
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - NET_ADMIN
  - SYS_MODULE
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'hostPath'
  {{- if .Values.global.prometheus.enabled }}
  hostPorts:
  - min: 9090
    max: 9090
  - min: 9091
    max: 9091
  {{- end }}
  hostNetwork: true
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:cilium-agent
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - gardener.kube-system.cilium-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener.cloud:psp:kube-system:cilium-agent
roleRef:
  kind: ClusterRole
  name: gardener.cloud:psp:kube-system:cilium-agent
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cilium
  namespace: {{ .Release.Namespace }}
{{- end }}
