# Specifies the resources for the hubble-relay pods
resources:
  requests:
    memory: 150Mi
  limits:
    memory: 1Gi

# Number of replicas run for the hubble-relay deployment.
numReplicas: 1

# Host to listen to. Specify an empty string to bind to all the interfaces.
listenHost: ""

# Port to listen to.
listenPort: "4245"

# Dial timeout to connect to the local hubble instance to receive peer information (e.g. "30s").
dialTimeout: ~

# Backoff duration to retry connecting to the local hubble instance in case of failure (e.g. "30s").
retryTimeout: ~

# Max number of flows that can be buffered for sorting before being sent to the client (per request) (e.g. 100).
sortBufferLenMax:

# When the per-request flows sort buffer is not full, a flow is drained every time this timeout is reached (only affects requests in follow-mode) (e.g. "1s").
sortBufferDrainTimeout:

tlsClientCertFile: /var/lib/hubble-relay/tls/client.crt

tlsClientKeyFile: /var/lib/hubble-relay/tls/client.key

tlsHubbleServerCAFiles: /var/lib/hubble-relay/tls/hubble-server-ca.crt

disableServerTls: true

# Port to use for the k8s service backed by hubble-relay pods.
servicePort: 80

gops: true

gopsPort: "9893"
