---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: hubble-ui
{{- if .Values.global.useProjectedTokenMount }}
automountServiceAccountToken: false
{{- end }}
