apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gardener-extension-admission-cilium
webhooks:
- name: mutation.cilium.networking.extension.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    resources:
    - shoots
  failurePolicy: Fail
  # Please make sure you are running `gardener@v1.42` or later before enabling this object selector.
  objectSelector:
    matchLabels:
      networking.extensions.gardener.cloud/cilium: "true"
  namespaceSelector: {}
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://localhost:9443/webhooks/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVzRENDQTVpZ0F3SUJBZ0lVSTg0ZzB0S2lkVzBKWVR1TjFCS2N5YmYvTnhBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1p6RUxNQWtHQTFVRUJoTUNSRVV4Q3pBSkJnTlZCQWdNQWtKWE1SRXdEd1lEVlFRSERBaFhZV3hzWkc5eQpaakVoTUI4R0ExVUVDZ3dZU1c1MFpYSnVaWFFnVjJsa1oybDBjeUJRZEhrZ1RIUmtNUlV3RXdZRFZRUUREQXhuCllYSmtaVzVsY2kxa1pYWXdIaGNOTWpNeE1ESXdNVEl5TlRRMVdoY05Nek14TURFM01USXlOVFExV2pCbk1Rc3cKQ1FZRFZRUUdFd0pFUlRFTE1Ba0dBMVVFQ0F3Q1FsY3hFVEFQQmdOVkJBY01DRmRoYkd4a2IzSm1NU0V3SHdZRApWUVFLREJoSmJuUmxjbTVsZENCWGFXUm5hWFJ6SUZCMGVTQk1kR1F4RlRBVEJnTlZCQU1NREdkaGNtUmxibVZ5CkxXUmxkakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLaDJ2QTdZYTBSTWUrajUKelluTkZCWGR1VytibzM4SUNxN29jeWphcDhXcjFKbFZNUDVSU2wxdVpsN3FjM2I1ZmQydUN6d3k3SnpIRm9NRApQazRKV3hleUNURlVxUWpWSXZEZ1R5OEdSZVZ1ZU1Ta2ZZSzNseG5oV1BUQmxneWlPVmh1cVNRZGpGSkFxRVZpCjh4UkxXdGFtamJEMjVXUkFSN3ZLV3FaK1dYVlZCMXdFUCtnQnFvYUdJQWlXRU1NMU0rRXlHYThhb2JqR2psWG8KL0FSbGJzUmN3VGlSbHBPM0FkMDVqZk9BRmN3RFNjM2xQMGdYQlB1TnJVekJyNE9FbEdiZ284Qjk4RHBrajZPNQp1RWhxVWF6dWR2R0dNU203blhDM0xGemxoK0FvZDkzdzlCSklvd3VLV3M3RlpYMURFeHhGaWJuOW5DdkxYRFJjCmhRUWN5ZDhDQXdFQUFhT0NBVkl3Z2dGT01JSUJLd1lEVlIwUkJJSUJJakNDQVI2Q0NXeHZZMkZzYUc5emRJSVUKYUc5emRDNWtiMk5yWlhJdWFXNTBaWEp1WVd5Q0kyZGhjbVJsYm1WeUxXVjRkR1Z1YzJsdmJpMWhaRzFwYzNOcApiMjR0WTJsc2FYVnRnaXBuWVhKa1pXNWxjaTFsZUhSbGJuTnBiMjR0WVdSdGFYTnphVzl1TFdOcGJHbDFiUzVuCllYSmtaVzZDTG1kaGNtUmxibVZ5TFdWNGRHVnVjMmx2YmkxaFpHMXBjM05wYjI0dFkybHNhWFZ0TG1kaGNtUmwKYmk1emRtT0NObWRoY21SbGJtVnlMV1Y0ZEdWdWMybHZiaTFoWkcxcGMzTnBiMjR0WTJsc2FYVnRMbWRoY21SbApiaTV6ZG1NdVkyeDFjM1JsY29JOFoyRnlaR1Z1WlhJdFpYaDBaVzV6YVc5dUxXRmtiV2x6YzJsdmJpMWphV3hwCmRXMHVaMkZ5WkdWdUxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc2h3Ui9BQUFCTUIwR0ExVWREZ1FXQkJTTkI3VDkKdVlqRERFcmwvQTR3QUwvVFJMQVVZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUkdydnBJSFpaMEkzOTE2MwpXT0ttVUkzeU5vMFVyVVpqVWorQTVLL2ZPR01nalJrZjFsWFdjZUxRNTRGRmxEREJtVDBaWFpaWjdwN1E5K2J3ClhZRUhiS0dUZTFBS3pPbzFEYW9xZUtTakYrdDFPZWM4MEdSVEhYUzBZQkFKWndvV3RrVmVxTHVHc0JwQzQxNncKNUV3TGNydEhTNU1xS0hJdk45Q3BJSUZmakFkcTExVENYS3dJdDVkczR1dmc2enJ3OFljUTNHdzdSYVNxUE9uVgp4Sm40OHdoUlBtek1vbjhrRDhGeW9KelhEQ3Y5Y21PdGlrY0U2NkErdC9XaEtqSFIxRGxTditTcTc5akppU05HCnZDR2hjU2oycHBORzZ2RTlKQ2dOUy9BVWM3aDAxd2lXalZPeTh1ZnRKMGwxVlM0NlNBNFdSeHRiallkS2QzU2oKRWE1czlBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
