run:
  concurrency: 4
  deadline: 10m

linters:
  disable:
    - unused

issues:
  exclude-use-default: false
  exclude:
  # typecheck:
  - "undeclared name: `.*`"
  - "\".*\" imported but not used"
  - "could not import .*"
  - ".* declared but not used"
  exclude-rules:
  - linters:
    - staticcheck
    text: "SA1019:" # Excludes messages where deprecated variables are used
