// +build !ignore_autogenerated

/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	cilium "github.com/gardener/gardener-extension-networking-cilium/pkg/apis/cilium"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Agent)(nil), (*cilium.Agent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Agent_To_cilium_Agent(a.(*Agent), b.(*cilium.Agent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Agent)(nil), (*Agent)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Agent_To_v1alpha1_Agent(a.(*cilium.Agent), b.(*Agent), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AutoDirectNodeRoutes)(nil), (*cilium.AutoDirectNodeRoutes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AutoDirectNodeRoutes_To_cilium_AutoDirectNodeRoutes(a.(*AutoDirectNodeRoutes), b.(*cilium.AutoDirectNodeRoutes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.AutoDirectNodeRoutes)(nil), (*AutoDirectNodeRoutes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_AutoDirectNodeRoutes_To_v1alpha1_AutoDirectNodeRoutes(a.(*cilium.AutoDirectNodeRoutes), b.(*AutoDirectNodeRoutes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Azure)(nil), (*cilium.Azure)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Azure_To_cilium_Azure(a.(*Azure), b.(*cilium.Azure), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Azure)(nil), (*Azure)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Azure_To_v1alpha1_Azure(a.(*cilium.Azure), b.(*Azure), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Bpf)(nil), (*cilium.Bpf)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Bpf_To_cilium_Bpf(a.(*Bpf), b.(*cilium.Bpf), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Bpf)(nil), (*Bpf)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Bpf_To_v1alpha1_Bpf(a.(*cilium.Bpf), b.(*Bpf), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CNI)(nil), (*cilium.CNI)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CNI_To_cilium_CNI(a.(*CNI), b.(*cilium.CNI), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.CNI)(nil), (*CNI)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_CNI_To_v1alpha1_CNI(a.(*cilium.CNI), b.(*CNI), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CleanBpfState)(nil), (*cilium.CleanBpfState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CleanBpfState_To_cilium_CleanBpfState(a.(*CleanBpfState), b.(*cilium.CleanBpfState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.CleanBpfState)(nil), (*CleanBpfState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_CleanBpfState_To_v1alpha1_CleanBpfState(a.(*cilium.CleanBpfState), b.(*CleanBpfState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CleanState)(nil), (*cilium.CleanState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CleanState_To_cilium_CleanState(a.(*CleanState), b.(*cilium.CleanState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.CleanState)(nil), (*CleanState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_CleanState_To_v1alpha1_CleanState(a.(*cilium.CleanState), b.(*CleanState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterName)(nil), (*cilium.ClusterName)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterName_To_cilium_ClusterName(a.(*ClusterName), b.(*cilium.ClusterName), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.ClusterName)(nil), (*ClusterName)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_ClusterName_To_v1alpha1_ClusterName(a.(*cilium.ClusterName), b.(*ClusterName), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ConfigEnable)(nil), (*cilium.ConfigEnable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ConfigEnable_To_cilium_ConfigEnable(a.(*ConfigEnable), b.(*cilium.ConfigEnable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.ConfigEnable)(nil), (*ConfigEnable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_ConfigEnable_To_v1alpha1_ConfigEnable(a.(*cilium.ConfigEnable), b.(*ConfigEnable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DaemonRunPath)(nil), (*cilium.DaemonRunPath)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DaemonRunPath_To_cilium_DaemonRunPath(a.(*DaemonRunPath), b.(*cilium.DaemonRunPath), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.DaemonRunPath)(nil), (*DaemonRunPath)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_DaemonRunPath_To_v1alpha1_DaemonRunPath(a.(*cilium.DaemonRunPath), b.(*DaemonRunPath), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Debug)(nil), (*cilium.Debug)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Debug_To_cilium_Debug(a.(*Debug), b.(*cilium.Debug), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Debug)(nil), (*Debug)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Debug_To_v1alpha1_Debug(a.(*cilium.Debug), b.(*Debug), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Encryption)(nil), (*cilium.Encryption)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Encryption_To_cilium_Encryption(a.(*Encryption), b.(*cilium.Encryption), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Encryption)(nil), (*Encryption)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Encryption_To_v1alpha1_Encryption(a.(*cilium.Encryption), b.(*Encryption), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EndpointRoutes)(nil), (*cilium.EndpointRoutes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EndpointRoutes_To_cilium_EndpointRoutes(a.(*EndpointRoutes), b.(*cilium.EndpointRoutes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.EndpointRoutes)(nil), (*EndpointRoutes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_EndpointRoutes_To_v1alpha1_EndpointRoutes(a.(*cilium.EndpointRoutes), b.(*EndpointRoutes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Eni)(nil), (*cilium.Eni)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Eni_To_cilium_Eni(a.(*Eni), b.(*cilium.Eni), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Eni)(nil), (*Eni)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Eni_To_v1alpha1_Eni(a.(*cilium.Eni), b.(*Eni), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EtcdConfig)(nil), (*cilium.EtcdConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_EtcdConfig_To_cilium_EtcdConfig(a.(*EtcdConfig), b.(*cilium.EtcdConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.EtcdConfig)(nil), (*EtcdConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_EtcdConfig_To_v1alpha1_EtcdConfig(a.(*cilium.EtcdConfig), b.(*EtcdConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExternalIP)(nil), (*cilium.ExternalIP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExternalIP_To_cilium_ExternalIP(a.(*ExternalIP), b.(*cilium.ExternalIP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.ExternalIP)(nil), (*ExternalIP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_ExternalIP_To_v1alpha1_ExternalIP(a.(*cilium.ExternalIP), b.(*ExternalIP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Flannel)(nil), (*cilium.Flannel)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Flannel_To_cilium_Flannel(a.(*Flannel), b.(*cilium.Flannel), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Flannel)(nil), (*Flannel)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Flannel_To_v1alpha1_Flannel(a.(*cilium.Flannel), b.(*Flannel), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GoogleGKE)(nil), (*cilium.GoogleGKE)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GoogleGKE_To_cilium_GoogleGKE(a.(*GoogleGKE), b.(*cilium.GoogleGKE), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.GoogleGKE)(nil), (*GoogleGKE)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_GoogleGKE_To_v1alpha1_GoogleGKE(a.(*cilium.GoogleGKE), b.(*GoogleGKE), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostServices)(nil), (*cilium.HostServices)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HostServices_To_cilium_HostServices(a.(*HostServices), b.(*cilium.HostServices), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.HostServices)(nil), (*HostServices)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_HostServices_To_v1alpha1_HostServices(a.(*cilium.HostServices), b.(*HostServices), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Hubble)(nil), (*cilium.Hubble)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Hubble_To_cilium_Hubble(a.(*Hubble), b.(*cilium.Hubble), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Hubble)(nil), (*Hubble)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Hubble_To_v1alpha1_Hubble(a.(*cilium.Hubble), b.(*Hubble), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPv4)(nil), (*cilium.IPv4)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPv4_To_cilium_IPv4(a.(*IPv4), b.(*cilium.IPv4), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.IPv4)(nil), (*IPv4)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_IPv4_To_v1alpha1_IPv4(a.(*cilium.IPv4), b.(*IPv4), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPv6)(nil), (*cilium.IPv6)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPv6_To_cilium_IPv6(a.(*IPv6), b.(*cilium.IPv6), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.IPv6)(nil), (*IPv6)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_IPv6_To_v1alpha1_IPv6(a.(*cilium.IPv6), b.(*IPv6), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IPvlan)(nil), (*cilium.IPvlan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IPvlan_To_cilium_IPvlan(a.(*IPvlan), b.(*cilium.IPvlan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.IPvlan)(nil), (*IPvlan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_IPvlan_To_v1alpha1_IPvlan(a.(*cilium.IPvlan), b.(*IPvlan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstallIPTableRules)(nil), (*cilium.InstallIPTableRules)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstallIPTableRules_To_cilium_InstallIPTableRules(a.(*InstallIPTableRules), b.(*cilium.InstallIPTableRules), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.InstallIPTableRules)(nil), (*InstallIPTableRules)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_InstallIPTableRules_To_v1alpha1_InstallIPTableRules(a.(*cilium.InstallIPTableRules), b.(*InstallIPTableRules), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*K8SIPv4PodCIDR)(nil), (*cilium.K8SIPv4PodCIDR)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_K8SIPv4PodCIDR_To_cilium_K8SIPv4PodCIDR(a.(*K8SIPv4PodCIDR), b.(*cilium.K8SIPv4PodCIDR), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.K8SIPv4PodCIDR)(nil), (*K8SIPv4PodCIDR)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_K8SIPv4PodCIDR_To_v1alpha1_K8SIPv4PodCIDR(a.(*cilium.K8SIPv4PodCIDR), b.(*K8SIPv4PodCIDR), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubeProxy)(nil), (*cilium.KubeProxy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KubeProxy_To_cilium_KubeProxy(a.(*KubeProxy), b.(*cilium.KubeProxy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.KubeProxy)(nil), (*KubeProxy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_KubeProxy_To_v1alpha1_KubeProxy(a.(*cilium.KubeProxy), b.(*KubeProxy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Masquerade)(nil), (*cilium.Masquerade)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Masquerade_To_cilium_Masquerade(a.(*Masquerade), b.(*cilium.Masquerade), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Masquerade)(nil), (*Masquerade)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Masquerade_To_v1alpha1_Masquerade(a.(*cilium.Masquerade), b.(*Masquerade), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkConfig)(nil), (*cilium.NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkConfig_To_cilium_NetworkConfig(a.(*NetworkConfig), b.(*cilium.NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.NetworkConfig)(nil), (*NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_NetworkConfig_To_v1alpha1_NetworkConfig(a.(*cilium.NetworkConfig), b.(*NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkStatus)(nil), (*cilium.NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkStatus_To_cilium_NetworkStatus(a.(*NetworkStatus), b.(*cilium.NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.NetworkStatus)(nil), (*NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_NetworkStatus_To_v1alpha1_NetworkStatus(a.(*cilium.NetworkStatus), b.(*NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeInit)(nil), (*cilium.NodeInit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeInit_To_cilium_NodeInit(a.(*NodeInit), b.(*cilium.NodeInit), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.NodeInit)(nil), (*NodeInit)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_NodeInit_To_v1alpha1_NodeInit(a.(*cilium.NodeInit), b.(*NodeInit), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Nodeport)(nil), (*cilium.Nodeport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Nodeport_To_cilium_Nodeport(a.(*Nodeport), b.(*cilium.Nodeport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Nodeport)(nil), (*Nodeport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Nodeport_To_v1alpha1_Nodeport(a.(*cilium.Nodeport), b.(*Nodeport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Operator)(nil), (*cilium.Operator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Operator_To_cilium_Operator(a.(*Operator), b.(*cilium.Operator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Operator)(nil), (*Operator)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Operator_To_v1alpha1_Operator(a.(*cilium.Operator), b.(*Operator), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OperatorPrometheus)(nil), (*cilium.OperatorPrometheus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OperatorPrometheus_To_cilium_OperatorPrometheus(a.(*OperatorPrometheus), b.(*cilium.OperatorPrometheus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.OperatorPrometheus)(nil), (*OperatorPrometheus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_OperatorPrometheus_To_v1alpha1_OperatorPrometheus(a.(*cilium.OperatorPrometheus), b.(*OperatorPrometheus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PolicyAuditMode)(nil), (*cilium.PolicyAuditMode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PolicyAuditMode_To_cilium_PolicyAuditMode(a.(*PolicyAuditMode), b.(*cilium.PolicyAuditMode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.PolicyAuditMode)(nil), (*PolicyAuditMode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_PolicyAuditMode_To_v1alpha1_PolicyAuditMode(a.(*cilium.PolicyAuditMode), b.(*PolicyAuditMode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Preflight)(nil), (*cilium.Preflight)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Preflight_To_cilium_Preflight(a.(*Preflight), b.(*cilium.Preflight), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Preflight)(nil), (*Preflight)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Preflight_To_v1alpha1_Preflight(a.(*cilium.Preflight), b.(*Preflight), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Prometheus)(nil), (*cilium.Prometheus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Prometheus_To_cilium_Prometheus(a.(*Prometheus), b.(*cilium.Prometheus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Prometheus)(nil), (*Prometheus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Prometheus_To_v1alpha1_Prometheus(a.(*cilium.Prometheus), b.(*Prometheus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Psp)(nil), (*cilium.Psp)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Psp_To_cilium_Psp(a.(*Psp), b.(*cilium.Psp), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.Psp)(nil), (*Psp)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_Psp_To_v1alpha1_Psp(a.(*cilium.Psp), b.(*Psp), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RemoteNodeIdentity)(nil), (*cilium.RemoteNodeIdentity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RemoteNodeIdentity_To_cilium_RemoteNodeIdentity(a.(*RemoteNodeIdentity), b.(*cilium.RemoteNodeIdentity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.RemoteNodeIdentity)(nil), (*RemoteNodeIdentity)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_RemoteNodeIdentity_To_v1alpha1_RemoteNodeIdentity(a.(*cilium.RemoteNodeIdentity), b.(*RemoteNodeIdentity), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SockOps)(nil), (*cilium.SockOps)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SockOps_To_cilium_SockOps(a.(*SockOps), b.(*cilium.SockOps), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.SockOps)(nil), (*SockOps)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_SockOps_To_v1alpha1_SockOps(a.(*cilium.SockOps), b.(*SockOps), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SynchronizeK8sNodes)(nil), (*cilium.SynchronizeK8sNodes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SynchronizeK8sNodes_To_cilium_SynchronizeK8sNodes(a.(*SynchronizeK8sNodes), b.(*cilium.SynchronizeK8sNodes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.SynchronizeK8sNodes)(nil), (*SynchronizeK8sNodes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_SynchronizeK8sNodes_To_v1alpha1_SynchronizeK8sNodes(a.(*cilium.SynchronizeK8sNodes), b.(*SynchronizeK8sNodes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TLSsecretsBackend)(nil), (*cilium.TLSsecretsBackend)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TLSsecretsBackend_To_cilium_TLSsecretsBackend(a.(*TLSsecretsBackend), b.(*cilium.TLSsecretsBackend), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.TLSsecretsBackend)(nil), (*TLSsecretsBackend)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_TLSsecretsBackend_To_v1alpha1_TLSsecretsBackend(a.(*cilium.TLSsecretsBackend), b.(*TLSsecretsBackend), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WellKnownIdentities)(nil), (*cilium.WellKnownIdentities)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WellKnownIdentities_To_cilium_WellKnownIdentities(a.(*WellKnownIdentities), b.(*cilium.WellKnownIdentities), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.WellKnownIdentities)(nil), (*WellKnownIdentities)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_WellKnownIdentities_To_v1alpha1_WellKnownIdentities(a.(*cilium.WellKnownIdentities), b.(*WellKnownIdentities), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*XTSocketFallback)(nil), (*cilium.XTSocketFallback)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_XTSocketFallback_To_cilium_XTSocketFallback(a.(*XTSocketFallback), b.(*cilium.XTSocketFallback), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*cilium.XTSocketFallback)(nil), (*XTSocketFallback)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_cilium_XTSocketFallback_To_v1alpha1_XTSocketFallback(a.(*cilium.XTSocketFallback), b.(*XTSocketFallback), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Agent_To_cilium_Agent(in *Agent, out *cilium.Agent, s conversion.Scope) error {
	out.AgentEnabled = in.AgentEnabled
	out.AgentSleepAfterInitEnabled = in.AgentSleepAfterInitEnabled
	out.AgentKeepDeprecatedLabelsEnabled = in.AgentKeepDeprecatedLabelsEnabled
	return nil
}

// Convert_v1alpha1_Agent_To_cilium_Agent is an autogenerated conversion function.
func Convert_v1alpha1_Agent_To_cilium_Agent(in *Agent, out *cilium.Agent, s conversion.Scope) error {
	return autoConvert_v1alpha1_Agent_To_cilium_Agent(in, out, s)
}

func autoConvert_cilium_Agent_To_v1alpha1_Agent(in *cilium.Agent, out *Agent, s conversion.Scope) error {
	out.AgentEnabled = in.AgentEnabled
	out.AgentSleepAfterInitEnabled = in.AgentSleepAfterInitEnabled
	out.AgentKeepDeprecatedLabelsEnabled = in.AgentKeepDeprecatedLabelsEnabled
	return nil
}

// Convert_cilium_Agent_To_v1alpha1_Agent is an autogenerated conversion function.
func Convert_cilium_Agent_To_v1alpha1_Agent(in *cilium.Agent, out *Agent, s conversion.Scope) error {
	return autoConvert_cilium_Agent_To_v1alpha1_Agent(in, out, s)
}

func autoConvert_v1alpha1_AutoDirectNodeRoutes_To_cilium_AutoDirectNodeRoutes(in *AutoDirectNodeRoutes, out *cilium.AutoDirectNodeRoutes, s conversion.Scope) error {
	out.AutoDirectNodeRoutesEnabled = in.AutoDirectNodeRoutesEnabled
	return nil
}

// Convert_v1alpha1_AutoDirectNodeRoutes_To_cilium_AutoDirectNodeRoutes is an autogenerated conversion function.
func Convert_v1alpha1_AutoDirectNodeRoutes_To_cilium_AutoDirectNodeRoutes(in *AutoDirectNodeRoutes, out *cilium.AutoDirectNodeRoutes, s conversion.Scope) error {
	return autoConvert_v1alpha1_AutoDirectNodeRoutes_To_cilium_AutoDirectNodeRoutes(in, out, s)
}

func autoConvert_cilium_AutoDirectNodeRoutes_To_v1alpha1_AutoDirectNodeRoutes(in *cilium.AutoDirectNodeRoutes, out *AutoDirectNodeRoutes, s conversion.Scope) error {
	out.AutoDirectNodeRoutesEnabled = in.AutoDirectNodeRoutesEnabled
	return nil
}

// Convert_cilium_AutoDirectNodeRoutes_To_v1alpha1_AutoDirectNodeRoutes is an autogenerated conversion function.
func Convert_cilium_AutoDirectNodeRoutes_To_v1alpha1_AutoDirectNodeRoutes(in *cilium.AutoDirectNodeRoutes, out *AutoDirectNodeRoutes, s conversion.Scope) error {
	return autoConvert_cilium_AutoDirectNodeRoutes_To_v1alpha1_AutoDirectNodeRoutes(in, out, s)
}

func autoConvert_v1alpha1_Azure_To_cilium_Azure(in *Azure, out *cilium.Azure, s conversion.Scope) error {
	out.AzureEnabled = in.AzureEnabled
	out.AzureResourceGroup = in.AzureResourceGroup
	out.AzureSubscriptionID = in.AzureSubscriptionID
	out.AzuretenantID = in.AzuretenantID
	out.AzureClientID = in.AzureClientID
	out.AzureClientSecret = in.AzureClientSecret
	return nil
}

// Convert_v1alpha1_Azure_To_cilium_Azure is an autogenerated conversion function.
func Convert_v1alpha1_Azure_To_cilium_Azure(in *Azure, out *cilium.Azure, s conversion.Scope) error {
	return autoConvert_v1alpha1_Azure_To_cilium_Azure(in, out, s)
}

func autoConvert_cilium_Azure_To_v1alpha1_Azure(in *cilium.Azure, out *Azure, s conversion.Scope) error {
	out.AzureEnabled = in.AzureEnabled
	out.AzureResourceGroup = in.AzureResourceGroup
	out.AzureSubscriptionID = in.AzureSubscriptionID
	out.AzuretenantID = in.AzuretenantID
	out.AzureClientID = in.AzureClientID
	out.AzureClientSecret = in.AzureClientSecret
	return nil
}

// Convert_cilium_Azure_To_v1alpha1_Azure is an autogenerated conversion function.
func Convert_cilium_Azure_To_v1alpha1_Azure(in *cilium.Azure, out *Azure, s conversion.Scope) error {
	return autoConvert_cilium_Azure_To_v1alpha1_Azure(in, out, s)
}

func autoConvert_v1alpha1_Bpf_To_cilium_Bpf(in *Bpf, out *cilium.Bpf, s conversion.Scope) error {
	out.WaitForMount = in.WaitForMount
	out.PreAllocateMaps = in.PreAllocateMaps
	out.CtTCPMax = in.CtTCPMax
	out.CtAnyMax = in.CtAnyMax
	out.MonitorAggregation = in.MonitorAggregation
	out.MonitorFlags = in.MonitorFlags
	return nil
}

// Convert_v1alpha1_Bpf_To_cilium_Bpf is an autogenerated conversion function.
func Convert_v1alpha1_Bpf_To_cilium_Bpf(in *Bpf, out *cilium.Bpf, s conversion.Scope) error {
	return autoConvert_v1alpha1_Bpf_To_cilium_Bpf(in, out, s)
}

func autoConvert_cilium_Bpf_To_v1alpha1_Bpf(in *cilium.Bpf, out *Bpf, s conversion.Scope) error {
	out.WaitForMount = in.WaitForMount
	out.PreAllocateMaps = in.PreAllocateMaps
	out.CtTCPMax = in.CtTCPMax
	out.CtAnyMax = in.CtAnyMax
	out.MonitorAggregation = in.MonitorAggregation
	out.MonitorFlags = in.MonitorFlags
	return nil
}

// Convert_cilium_Bpf_To_v1alpha1_Bpf is an autogenerated conversion function.
func Convert_cilium_Bpf_To_v1alpha1_Bpf(in *cilium.Bpf, out *Bpf, s conversion.Scope) error {
	return autoConvert_cilium_Bpf_To_v1alpha1_Bpf(in, out, s)
}

func autoConvert_v1alpha1_CNI_To_cilium_CNI(in *CNI, out *cilium.CNI, s conversion.Scope) error {
	out.CniInstallEnabled = in.CniInstallEnabled
	out.CniChainginMode = in.CniChainginMode
	out.CniCustomConfigEnabled = in.CniCustomConfigEnabled
	out.CniConfigPath = in.CniConfigPath
	out.CniBinPath = in.CniBinPath
	out.CniConfigMapKey = in.CniConfigMapKey
	out.CniConfigMap = in.CniConfigMap
	out.CniConfFileMountPath = in.CniConfFileMountPath
	out.CniHostConfDirMountPath = in.CniHostConfDirMountPath
	return nil
}

// Convert_v1alpha1_CNI_To_cilium_CNI is an autogenerated conversion function.
func Convert_v1alpha1_CNI_To_cilium_CNI(in *CNI, out *cilium.CNI, s conversion.Scope) error {
	return autoConvert_v1alpha1_CNI_To_cilium_CNI(in, out, s)
}

func autoConvert_cilium_CNI_To_v1alpha1_CNI(in *cilium.CNI, out *CNI, s conversion.Scope) error {
	out.CniInstallEnabled = in.CniInstallEnabled
	out.CniChainginMode = in.CniChainginMode
	out.CniCustomConfigEnabled = in.CniCustomConfigEnabled
	out.CniConfigPath = in.CniConfigPath
	out.CniBinPath = in.CniBinPath
	out.CniConfigMapKey = in.CniConfigMapKey
	out.CniConfigMap = in.CniConfigMap
	out.CniConfFileMountPath = in.CniConfFileMountPath
	out.CniHostConfDirMountPath = in.CniHostConfDirMountPath
	return nil
}

// Convert_cilium_CNI_To_v1alpha1_CNI is an autogenerated conversion function.
func Convert_cilium_CNI_To_v1alpha1_CNI(in *cilium.CNI, out *CNI, s conversion.Scope) error {
	return autoConvert_cilium_CNI_To_v1alpha1_CNI(in, out, s)
}

func autoConvert_v1alpha1_CleanBpfState_To_cilium_CleanBpfState(in *CleanBpfState, out *cilium.CleanBpfState, s conversion.Scope) error {
	out.CleanBpfStateEnabled = in.CleanBpfStateEnabled
	return nil
}

// Convert_v1alpha1_CleanBpfState_To_cilium_CleanBpfState is an autogenerated conversion function.
func Convert_v1alpha1_CleanBpfState_To_cilium_CleanBpfState(in *CleanBpfState, out *cilium.CleanBpfState, s conversion.Scope) error {
	return autoConvert_v1alpha1_CleanBpfState_To_cilium_CleanBpfState(in, out, s)
}

func autoConvert_cilium_CleanBpfState_To_v1alpha1_CleanBpfState(in *cilium.CleanBpfState, out *CleanBpfState, s conversion.Scope) error {
	out.CleanBpfStateEnabled = in.CleanBpfStateEnabled
	return nil
}

// Convert_cilium_CleanBpfState_To_v1alpha1_CleanBpfState is an autogenerated conversion function.
func Convert_cilium_CleanBpfState_To_v1alpha1_CleanBpfState(in *cilium.CleanBpfState, out *CleanBpfState, s conversion.Scope) error {
	return autoConvert_cilium_CleanBpfState_To_v1alpha1_CleanBpfState(in, out, s)
}

func autoConvert_v1alpha1_CleanState_To_cilium_CleanState(in *CleanState, out *cilium.CleanState, s conversion.Scope) error {
	out.CleanStateEnabled = in.CleanStateEnabled
	return nil
}

// Convert_v1alpha1_CleanState_To_cilium_CleanState is an autogenerated conversion function.
func Convert_v1alpha1_CleanState_To_cilium_CleanState(in *CleanState, out *cilium.CleanState, s conversion.Scope) error {
	return autoConvert_v1alpha1_CleanState_To_cilium_CleanState(in, out, s)
}

func autoConvert_cilium_CleanState_To_v1alpha1_CleanState(in *cilium.CleanState, out *CleanState, s conversion.Scope) error {
	out.CleanStateEnabled = in.CleanStateEnabled
	return nil
}

// Convert_cilium_CleanState_To_v1alpha1_CleanState is an autogenerated conversion function.
func Convert_cilium_CleanState_To_v1alpha1_CleanState(in *cilium.CleanState, out *CleanState, s conversion.Scope) error {
	return autoConvert_cilium_CleanState_To_v1alpha1_CleanState(in, out, s)
}

func autoConvert_v1alpha1_ClusterName_To_cilium_ClusterName(in *ClusterName, out *cilium.ClusterName, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	return nil
}

// Convert_v1alpha1_ClusterName_To_cilium_ClusterName is an autogenerated conversion function.
func Convert_v1alpha1_ClusterName_To_cilium_ClusterName(in *ClusterName, out *cilium.ClusterName, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterName_To_cilium_ClusterName(in, out, s)
}

func autoConvert_cilium_ClusterName_To_v1alpha1_ClusterName(in *cilium.ClusterName, out *ClusterName, s conversion.Scope) error {
	out.ClusterName = in.ClusterName
	return nil
}

// Convert_cilium_ClusterName_To_v1alpha1_ClusterName is an autogenerated conversion function.
func Convert_cilium_ClusterName_To_v1alpha1_ClusterName(in *cilium.ClusterName, out *ClusterName, s conversion.Scope) error {
	return autoConvert_cilium_ClusterName_To_v1alpha1_ClusterName(in, out, s)
}

func autoConvert_v1alpha1_ConfigEnable_To_cilium_ConfigEnable(in *ConfigEnable, out *cilium.ConfigEnable, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_v1alpha1_ConfigEnable_To_cilium_ConfigEnable is an autogenerated conversion function.
func Convert_v1alpha1_ConfigEnable_To_cilium_ConfigEnable(in *ConfigEnable, out *cilium.ConfigEnable, s conversion.Scope) error {
	return autoConvert_v1alpha1_ConfigEnable_To_cilium_ConfigEnable(in, out, s)
}

func autoConvert_cilium_ConfigEnable_To_v1alpha1_ConfigEnable(in *cilium.ConfigEnable, out *ConfigEnable, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_cilium_ConfigEnable_To_v1alpha1_ConfigEnable is an autogenerated conversion function.
func Convert_cilium_ConfigEnable_To_v1alpha1_ConfigEnable(in *cilium.ConfigEnable, out *ConfigEnable, s conversion.Scope) error {
	return autoConvert_cilium_ConfigEnable_To_v1alpha1_ConfigEnable(in, out, s)
}

func autoConvert_v1alpha1_DaemonRunPath_To_cilium_DaemonRunPath(in *DaemonRunPath, out *cilium.DaemonRunPath, s conversion.Scope) error {
	out.DaemonRunPath = in.DaemonRunPath
	return nil
}

// Convert_v1alpha1_DaemonRunPath_To_cilium_DaemonRunPath is an autogenerated conversion function.
func Convert_v1alpha1_DaemonRunPath_To_cilium_DaemonRunPath(in *DaemonRunPath, out *cilium.DaemonRunPath, s conversion.Scope) error {
	return autoConvert_v1alpha1_DaemonRunPath_To_cilium_DaemonRunPath(in, out, s)
}

func autoConvert_cilium_DaemonRunPath_To_v1alpha1_DaemonRunPath(in *cilium.DaemonRunPath, out *DaemonRunPath, s conversion.Scope) error {
	out.DaemonRunPath = in.DaemonRunPath
	return nil
}

// Convert_cilium_DaemonRunPath_To_v1alpha1_DaemonRunPath is an autogenerated conversion function.
func Convert_cilium_DaemonRunPath_To_v1alpha1_DaemonRunPath(in *cilium.DaemonRunPath, out *DaemonRunPath, s conversion.Scope) error {
	return autoConvert_cilium_DaemonRunPath_To_v1alpha1_DaemonRunPath(in, out, s)
}

func autoConvert_v1alpha1_Debug_To_cilium_Debug(in *Debug, out *cilium.Debug, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_v1alpha1_Debug_To_cilium_Debug is an autogenerated conversion function.
func Convert_v1alpha1_Debug_To_cilium_Debug(in *Debug, out *cilium.Debug, s conversion.Scope) error {
	return autoConvert_v1alpha1_Debug_To_cilium_Debug(in, out, s)
}

func autoConvert_cilium_Debug_To_v1alpha1_Debug(in *cilium.Debug, out *Debug, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_cilium_Debug_To_v1alpha1_Debug is an autogenerated conversion function.
func Convert_cilium_Debug_To_v1alpha1_Debug(in *cilium.Debug, out *Debug, s conversion.Scope) error {
	return autoConvert_cilium_Debug_To_v1alpha1_Debug(in, out, s)
}

func autoConvert_v1alpha1_Encryption_To_cilium_Encryption(in *Encryption, out *cilium.Encryption, s conversion.Scope) error {
	out.EncryptionEnabled = in.EncryptionEnabled
	out.KeyFile = in.KeyFile
	out.MountPath = in.MountPath
	out.SecretName = in.SecretName
	out.NodeEncryption = in.NodeEncryption
	out.Interface = in.Interface
	return nil
}

// Convert_v1alpha1_Encryption_To_cilium_Encryption is an autogenerated conversion function.
func Convert_v1alpha1_Encryption_To_cilium_Encryption(in *Encryption, out *cilium.Encryption, s conversion.Scope) error {
	return autoConvert_v1alpha1_Encryption_To_cilium_Encryption(in, out, s)
}

func autoConvert_cilium_Encryption_To_v1alpha1_Encryption(in *cilium.Encryption, out *Encryption, s conversion.Scope) error {
	out.EncryptionEnabled = in.EncryptionEnabled
	out.KeyFile = in.KeyFile
	out.MountPath = in.MountPath
	out.SecretName = in.SecretName
	out.NodeEncryption = in.NodeEncryption
	out.Interface = in.Interface
	return nil
}

// Convert_cilium_Encryption_To_v1alpha1_Encryption is an autogenerated conversion function.
func Convert_cilium_Encryption_To_v1alpha1_Encryption(in *cilium.Encryption, out *Encryption, s conversion.Scope) error {
	return autoConvert_cilium_Encryption_To_v1alpha1_Encryption(in, out, s)
}

func autoConvert_v1alpha1_EndpointRoutes_To_cilium_EndpointRoutes(in *EndpointRoutes, out *cilium.EndpointRoutes, s conversion.Scope) error {
	out.EndpointRoutesEnabled = in.EndpointRoutesEnabled
	return nil
}

// Convert_v1alpha1_EndpointRoutes_To_cilium_EndpointRoutes is an autogenerated conversion function.
func Convert_v1alpha1_EndpointRoutes_To_cilium_EndpointRoutes(in *EndpointRoutes, out *cilium.EndpointRoutes, s conversion.Scope) error {
	return autoConvert_v1alpha1_EndpointRoutes_To_cilium_EndpointRoutes(in, out, s)
}

func autoConvert_cilium_EndpointRoutes_To_v1alpha1_EndpointRoutes(in *cilium.EndpointRoutes, out *EndpointRoutes, s conversion.Scope) error {
	out.EndpointRoutesEnabled = in.EndpointRoutesEnabled
	return nil
}

// Convert_cilium_EndpointRoutes_To_v1alpha1_EndpointRoutes is an autogenerated conversion function.
func Convert_cilium_EndpointRoutes_To_v1alpha1_EndpointRoutes(in *cilium.EndpointRoutes, out *EndpointRoutes, s conversion.Scope) error {
	return autoConvert_cilium_EndpointRoutes_To_v1alpha1_EndpointRoutes(in, out, s)
}

func autoConvert_v1alpha1_Eni_To_cilium_Eni(in *Eni, out *cilium.Eni, s conversion.Scope) error {
	out.EniEnabled = in.EniEnabled
	out.EgressMasqueradeInterfaces = in.EgressMasqueradeInterfaces
	return nil
}

// Convert_v1alpha1_Eni_To_cilium_Eni is an autogenerated conversion function.
func Convert_v1alpha1_Eni_To_cilium_Eni(in *Eni, out *cilium.Eni, s conversion.Scope) error {
	return autoConvert_v1alpha1_Eni_To_cilium_Eni(in, out, s)
}

func autoConvert_cilium_Eni_To_v1alpha1_Eni(in *cilium.Eni, out *Eni, s conversion.Scope) error {
	out.EniEnabled = in.EniEnabled
	out.EgressMasqueradeInterfaces = in.EgressMasqueradeInterfaces
	return nil
}

// Convert_cilium_Eni_To_v1alpha1_Eni is an autogenerated conversion function.
func Convert_cilium_Eni_To_v1alpha1_Eni(in *cilium.Eni, out *Eni, s conversion.Scope) error {
	return autoConvert_cilium_Eni_To_v1alpha1_Eni(in, out, s)
}

func autoConvert_v1alpha1_EtcdConfig_To_cilium_EtcdConfig(in *EtcdConfig, out *cilium.EtcdConfig, s conversion.Scope) error {
	out.EtcdEnabled = in.EtcdEnabled
	out.EtcdManaged = in.EtcdManaged
	out.EtcdsslEnabled = in.EtcdsslEnabled
	out.EtcdEndpoints = *(*[]string)(unsafe.Pointer(&in.EtcdEndpoints))
	out.CAFile = in.CAFile
	out.CertFile = in.CertFile
	out.KeyFile = in.KeyFile
	return nil
}

// Convert_v1alpha1_EtcdConfig_To_cilium_EtcdConfig is an autogenerated conversion function.
func Convert_v1alpha1_EtcdConfig_To_cilium_EtcdConfig(in *EtcdConfig, out *cilium.EtcdConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_EtcdConfig_To_cilium_EtcdConfig(in, out, s)
}

func autoConvert_cilium_EtcdConfig_To_v1alpha1_EtcdConfig(in *cilium.EtcdConfig, out *EtcdConfig, s conversion.Scope) error {
	out.EtcdEnabled = in.EtcdEnabled
	out.EtcdManaged = in.EtcdManaged
	out.EtcdsslEnabled = in.EtcdsslEnabled
	out.EtcdEndpoints = *(*[]string)(unsafe.Pointer(&in.EtcdEndpoints))
	out.CAFile = in.CAFile
	out.CertFile = in.CertFile
	out.KeyFile = in.KeyFile
	return nil
}

// Convert_cilium_EtcdConfig_To_v1alpha1_EtcdConfig is an autogenerated conversion function.
func Convert_cilium_EtcdConfig_To_v1alpha1_EtcdConfig(in *cilium.EtcdConfig, out *EtcdConfig, s conversion.Scope) error {
	return autoConvert_cilium_EtcdConfig_To_v1alpha1_EtcdConfig(in, out, s)
}

func autoConvert_v1alpha1_ExternalIP_To_cilium_ExternalIP(in *ExternalIP, out *cilium.ExternalIP, s conversion.Scope) error {
	out.ExternalIPEnabled = in.ExternalIPEnabled
	return nil
}

// Convert_v1alpha1_ExternalIP_To_cilium_ExternalIP is an autogenerated conversion function.
func Convert_v1alpha1_ExternalIP_To_cilium_ExternalIP(in *ExternalIP, out *cilium.ExternalIP, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExternalIP_To_cilium_ExternalIP(in, out, s)
}

func autoConvert_cilium_ExternalIP_To_v1alpha1_ExternalIP(in *cilium.ExternalIP, out *ExternalIP, s conversion.Scope) error {
	out.ExternalIPEnabled = in.ExternalIPEnabled
	return nil
}

// Convert_cilium_ExternalIP_To_v1alpha1_ExternalIP is an autogenerated conversion function.
func Convert_cilium_ExternalIP_To_v1alpha1_ExternalIP(in *cilium.ExternalIP, out *ExternalIP, s conversion.Scope) error {
	return autoConvert_cilium_ExternalIP_To_v1alpha1_ExternalIP(in, out, s)
}

func autoConvert_v1alpha1_Flannel_To_cilium_Flannel(in *Flannel, out *cilium.Flannel, s conversion.Scope) error {
	out.FlannelEnabled = in.FlannelEnabled
	out.MasterDevice = in.MasterDevice
	out.UninstallOnExit = in.UninstallOnExit
	return nil
}

// Convert_v1alpha1_Flannel_To_cilium_Flannel is an autogenerated conversion function.
func Convert_v1alpha1_Flannel_To_cilium_Flannel(in *Flannel, out *cilium.Flannel, s conversion.Scope) error {
	return autoConvert_v1alpha1_Flannel_To_cilium_Flannel(in, out, s)
}

func autoConvert_cilium_Flannel_To_v1alpha1_Flannel(in *cilium.Flannel, out *Flannel, s conversion.Scope) error {
	out.FlannelEnabled = in.FlannelEnabled
	out.MasterDevice = in.MasterDevice
	out.UninstallOnExit = in.UninstallOnExit
	return nil
}

// Convert_cilium_Flannel_To_v1alpha1_Flannel is an autogenerated conversion function.
func Convert_cilium_Flannel_To_v1alpha1_Flannel(in *cilium.Flannel, out *Flannel, s conversion.Scope) error {
	return autoConvert_cilium_Flannel_To_v1alpha1_Flannel(in, out, s)
}

func autoConvert_v1alpha1_GoogleGKE_To_cilium_GoogleGKE(in *GoogleGKE, out *cilium.GoogleGKE, s conversion.Scope) error {
	out.GoogleGkeEnabled = in.GoogleGkeEnabled
	return nil
}

// Convert_v1alpha1_GoogleGKE_To_cilium_GoogleGKE is an autogenerated conversion function.
func Convert_v1alpha1_GoogleGKE_To_cilium_GoogleGKE(in *GoogleGKE, out *cilium.GoogleGKE, s conversion.Scope) error {
	return autoConvert_v1alpha1_GoogleGKE_To_cilium_GoogleGKE(in, out, s)
}

func autoConvert_cilium_GoogleGKE_To_v1alpha1_GoogleGKE(in *cilium.GoogleGKE, out *GoogleGKE, s conversion.Scope) error {
	out.GoogleGkeEnabled = in.GoogleGkeEnabled
	return nil
}

// Convert_cilium_GoogleGKE_To_v1alpha1_GoogleGKE is an autogenerated conversion function.
func Convert_cilium_GoogleGKE_To_v1alpha1_GoogleGKE(in *cilium.GoogleGKE, out *GoogleGKE, s conversion.Scope) error {
	return autoConvert_cilium_GoogleGKE_To_v1alpha1_GoogleGKE(in, out, s)
}

func autoConvert_v1alpha1_HostServices_To_cilium_HostServices(in *HostServices, out *cilium.HostServices, s conversion.Scope) error {
	out.HostServicesEnabled = in.HostServicesEnabled
	out.Protocols = in.Protocols
	return nil
}

// Convert_v1alpha1_HostServices_To_cilium_HostServices is an autogenerated conversion function.
func Convert_v1alpha1_HostServices_To_cilium_HostServices(in *HostServices, out *cilium.HostServices, s conversion.Scope) error {
	return autoConvert_v1alpha1_HostServices_To_cilium_HostServices(in, out, s)
}

func autoConvert_cilium_HostServices_To_v1alpha1_HostServices(in *cilium.HostServices, out *HostServices, s conversion.Scope) error {
	out.HostServicesEnabled = in.HostServicesEnabled
	out.Protocols = in.Protocols
	return nil
}

// Convert_cilium_HostServices_To_v1alpha1_HostServices is an autogenerated conversion function.
func Convert_cilium_HostServices_To_v1alpha1_HostServices(in *cilium.HostServices, out *HostServices, s conversion.Scope) error {
	return autoConvert_cilium_HostServices_To_v1alpha1_HostServices(in, out, s)
}

func autoConvert_v1alpha1_Hubble_To_cilium_Hubble(in *Hubble, out *cilium.Hubble, s conversion.Scope) error {
	out.HubbleEnabled = in.HubbleEnabled
	out.ListenAddresses = *(*[]string)(unsafe.Pointer(&in.ListenAddresses))
	out.EventQueueSize = in.EventQueueSize
	out.FlowBufferSize = in.FlowBufferSize
	out.MetricServer = in.MetricServer
	out.Metrics = *(*[]string)(unsafe.Pointer(&in.Metrics))
	out.UI = in.UI
	return nil
}

// Convert_v1alpha1_Hubble_To_cilium_Hubble is an autogenerated conversion function.
func Convert_v1alpha1_Hubble_To_cilium_Hubble(in *Hubble, out *cilium.Hubble, s conversion.Scope) error {
	return autoConvert_v1alpha1_Hubble_To_cilium_Hubble(in, out, s)
}

func autoConvert_cilium_Hubble_To_v1alpha1_Hubble(in *cilium.Hubble, out *Hubble, s conversion.Scope) error {
	out.HubbleEnabled = in.HubbleEnabled
	out.ListenAddresses = *(*[]string)(unsafe.Pointer(&in.ListenAddresses))
	out.EventQueueSize = in.EventQueueSize
	out.FlowBufferSize = in.FlowBufferSize
	out.MetricServer = in.MetricServer
	out.Metrics = *(*[]string)(unsafe.Pointer(&in.Metrics))
	out.UI = in.UI
	return nil
}

// Convert_cilium_Hubble_To_v1alpha1_Hubble is an autogenerated conversion function.
func Convert_cilium_Hubble_To_v1alpha1_Hubble(in *cilium.Hubble, out *Hubble, s conversion.Scope) error {
	return autoConvert_cilium_Hubble_To_v1alpha1_Hubble(in, out, s)
}

func autoConvert_v1alpha1_IPv4_To_cilium_IPv4(in *IPv4, out *cilium.IPv4, s conversion.Scope) error {
	out.IPv4Enabled = in.IPv4Enabled
	return nil
}

// Convert_v1alpha1_IPv4_To_cilium_IPv4 is an autogenerated conversion function.
func Convert_v1alpha1_IPv4_To_cilium_IPv4(in *IPv4, out *cilium.IPv4, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPv4_To_cilium_IPv4(in, out, s)
}

func autoConvert_cilium_IPv4_To_v1alpha1_IPv4(in *cilium.IPv4, out *IPv4, s conversion.Scope) error {
	out.IPv4Enabled = in.IPv4Enabled
	return nil
}

// Convert_cilium_IPv4_To_v1alpha1_IPv4 is an autogenerated conversion function.
func Convert_cilium_IPv4_To_v1alpha1_IPv4(in *cilium.IPv4, out *IPv4, s conversion.Scope) error {
	return autoConvert_cilium_IPv4_To_v1alpha1_IPv4(in, out, s)
}

func autoConvert_v1alpha1_IPv6_To_cilium_IPv6(in *IPv6, out *cilium.IPv6, s conversion.Scope) error {
	out.IPv6Enabled = in.IPv6Enabled
	return nil
}

// Convert_v1alpha1_IPv6_To_cilium_IPv6 is an autogenerated conversion function.
func Convert_v1alpha1_IPv6_To_cilium_IPv6(in *IPv6, out *cilium.IPv6, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPv6_To_cilium_IPv6(in, out, s)
}

func autoConvert_cilium_IPv6_To_v1alpha1_IPv6(in *cilium.IPv6, out *IPv6, s conversion.Scope) error {
	out.IPv6Enabled = in.IPv6Enabled
	return nil
}

// Convert_cilium_IPv6_To_v1alpha1_IPv6 is an autogenerated conversion function.
func Convert_cilium_IPv6_To_v1alpha1_IPv6(in *cilium.IPv6, out *IPv6, s conversion.Scope) error {
	return autoConvert_cilium_IPv6_To_v1alpha1_IPv6(in, out, s)
}

func autoConvert_v1alpha1_IPvlan_To_cilium_IPvlan(in *IPvlan, out *cilium.IPvlan, s conversion.Scope) error {
	out.IPvlanEnabled = in.IPvlanEnabled
	out.MasterDevice = in.MasterDevice
	out.IPVlanMode = cilium.IPVlanMode(in.IPVlanMode)
	return nil
}

// Convert_v1alpha1_IPvlan_To_cilium_IPvlan is an autogenerated conversion function.
func Convert_v1alpha1_IPvlan_To_cilium_IPvlan(in *IPvlan, out *cilium.IPvlan, s conversion.Scope) error {
	return autoConvert_v1alpha1_IPvlan_To_cilium_IPvlan(in, out, s)
}

func autoConvert_cilium_IPvlan_To_v1alpha1_IPvlan(in *cilium.IPvlan, out *IPvlan, s conversion.Scope) error {
	out.IPvlanEnabled = in.IPvlanEnabled
	out.MasterDevice = in.MasterDevice
	out.IPVlanMode = IPVlanMode(in.IPVlanMode)
	return nil
}

// Convert_cilium_IPvlan_To_v1alpha1_IPvlan is an autogenerated conversion function.
func Convert_cilium_IPvlan_To_v1alpha1_IPvlan(in *cilium.IPvlan, out *IPvlan, s conversion.Scope) error {
	return autoConvert_cilium_IPvlan_To_v1alpha1_IPvlan(in, out, s)
}

func autoConvert_v1alpha1_InstallIPTableRules_To_cilium_InstallIPTableRules(in *InstallIPTableRules, out *cilium.InstallIPTableRules, s conversion.Scope) error {
	out.InstallIPTableRulesEnabled = in.InstallIPTableRulesEnabled
	return nil
}

// Convert_v1alpha1_InstallIPTableRules_To_cilium_InstallIPTableRules is an autogenerated conversion function.
func Convert_v1alpha1_InstallIPTableRules_To_cilium_InstallIPTableRules(in *InstallIPTableRules, out *cilium.InstallIPTableRules, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstallIPTableRules_To_cilium_InstallIPTableRules(in, out, s)
}

func autoConvert_cilium_InstallIPTableRules_To_v1alpha1_InstallIPTableRules(in *cilium.InstallIPTableRules, out *InstallIPTableRules, s conversion.Scope) error {
	out.InstallIPTableRulesEnabled = in.InstallIPTableRulesEnabled
	return nil
}

// Convert_cilium_InstallIPTableRules_To_v1alpha1_InstallIPTableRules is an autogenerated conversion function.
func Convert_cilium_InstallIPTableRules_To_v1alpha1_InstallIPTableRules(in *cilium.InstallIPTableRules, out *InstallIPTableRules, s conversion.Scope) error {
	return autoConvert_cilium_InstallIPTableRules_To_v1alpha1_InstallIPTableRules(in, out, s)
}

func autoConvert_v1alpha1_K8SIPv4PodCIDR_To_cilium_K8SIPv4PodCIDR(in *K8SIPv4PodCIDR, out *cilium.K8SIPv4PodCIDR, s conversion.Scope) error {
	out.K8SIPv4PodCIDREnabled = in.K8SIPv4PodCIDREnabled
	return nil
}

// Convert_v1alpha1_K8SIPv4PodCIDR_To_cilium_K8SIPv4PodCIDR is an autogenerated conversion function.
func Convert_v1alpha1_K8SIPv4PodCIDR_To_cilium_K8SIPv4PodCIDR(in *K8SIPv4PodCIDR, out *cilium.K8SIPv4PodCIDR, s conversion.Scope) error {
	return autoConvert_v1alpha1_K8SIPv4PodCIDR_To_cilium_K8SIPv4PodCIDR(in, out, s)
}

func autoConvert_cilium_K8SIPv4PodCIDR_To_v1alpha1_K8SIPv4PodCIDR(in *cilium.K8SIPv4PodCIDR, out *K8SIPv4PodCIDR, s conversion.Scope) error {
	out.K8SIPv4PodCIDREnabled = in.K8SIPv4PodCIDREnabled
	return nil
}

// Convert_cilium_K8SIPv4PodCIDR_To_v1alpha1_K8SIPv4PodCIDR is an autogenerated conversion function.
func Convert_cilium_K8SIPv4PodCIDR_To_v1alpha1_K8SIPv4PodCIDR(in *cilium.K8SIPv4PodCIDR, out *K8SIPv4PodCIDR, s conversion.Scope) error {
	return autoConvert_cilium_K8SIPv4PodCIDR_To_v1alpha1_K8SIPv4PodCIDR(in, out, s)
}

func autoConvert_v1alpha1_KubeProxy_To_cilium_KubeProxy(in *KubeProxy, out *cilium.KubeProxy, s conversion.Scope) error {
	out.KubeProxyEnabled = in.KubeProxyEnabled
	return nil
}

// Convert_v1alpha1_KubeProxy_To_cilium_KubeProxy is an autogenerated conversion function.
func Convert_v1alpha1_KubeProxy_To_cilium_KubeProxy(in *KubeProxy, out *cilium.KubeProxy, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubeProxy_To_cilium_KubeProxy(in, out, s)
}

func autoConvert_cilium_KubeProxy_To_v1alpha1_KubeProxy(in *cilium.KubeProxy, out *KubeProxy, s conversion.Scope) error {
	out.KubeProxyEnabled = in.KubeProxyEnabled
	return nil
}

// Convert_cilium_KubeProxy_To_v1alpha1_KubeProxy is an autogenerated conversion function.
func Convert_cilium_KubeProxy_To_v1alpha1_KubeProxy(in *cilium.KubeProxy, out *KubeProxy, s conversion.Scope) error {
	return autoConvert_cilium_KubeProxy_To_v1alpha1_KubeProxy(in, out, s)
}

func autoConvert_v1alpha1_Masquerade_To_cilium_Masquerade(in *Masquerade, out *cilium.Masquerade, s conversion.Scope) error {
	out.MasqueradeEnabled = in.MasqueradeEnabled
	return nil
}

// Convert_v1alpha1_Masquerade_To_cilium_Masquerade is an autogenerated conversion function.
func Convert_v1alpha1_Masquerade_To_cilium_Masquerade(in *Masquerade, out *cilium.Masquerade, s conversion.Scope) error {
	return autoConvert_v1alpha1_Masquerade_To_cilium_Masquerade(in, out, s)
}

func autoConvert_cilium_Masquerade_To_v1alpha1_Masquerade(in *cilium.Masquerade, out *Masquerade, s conversion.Scope) error {
	out.MasqueradeEnabled = in.MasqueradeEnabled
	return nil
}

// Convert_cilium_Masquerade_To_v1alpha1_Masquerade is an autogenerated conversion function.
func Convert_cilium_Masquerade_To_v1alpha1_Masquerade(in *cilium.Masquerade, out *Masquerade, s conversion.Scope) error {
	return autoConvert_cilium_Masquerade_To_v1alpha1_Masquerade(in, out, s)
}

func autoConvert_v1alpha1_NetworkConfig_To_cilium_NetworkConfig(in *NetworkConfig, out *cilium.NetworkConfig, s conversion.Scope) error {
	out.Debug = (*cilium.Debug)(unsafe.Pointer(in.Debug))
	if err := Convert_v1alpha1_GoogleGKE_To_cilium_GoogleGKE(&in.GoogleGKE, &out.GoogleGKE, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_NodeInit_To_cilium_NodeInit(&in.NodeInit, &out.NodeInit, s); err != nil {
		return err
	}
	out.Operator = (*cilium.Operator)(unsafe.Pointer(in.Operator))
	out.ClusterName = (*cilium.ClusterName)(unsafe.Pointer(in.ClusterName))
	out.Preflight = (*cilium.Preflight)(unsafe.Pointer(in.Preflight))
	out.CleanState = (*cilium.CleanState)(unsafe.Pointer(in.CleanState))
	out.CleanBpfState = (*cilium.CleanBpfState)(unsafe.Pointer(in.CleanBpfState))
	out.Bpf = (*cilium.Bpf)(unsafe.Pointer(in.Bpf))
	out.HostServices = (*cilium.HostServices)(unsafe.Pointer(in.HostServices))
	out.SockOps = (*cilium.SockOps)(unsafe.Pointer(in.SockOps))
	out.InstallIPTableRules = (*cilium.InstallIPTableRules)(unsafe.Pointer(in.InstallIPTableRules))
	out.Prometheus = (*cilium.Prometheus)(unsafe.Pointer(in.Prometheus))
	if err := Convert_v1alpha1_SynchronizeK8sNodes_To_cilium_SynchronizeK8sNodes(&in.SynchronizeK8sNodes, &out.SynchronizeK8sNodes, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RemoteNodeIdentity_To_cilium_RemoteNodeIdentity(&in.RemoteNodeIdentity, &out.RemoteNodeIdentity, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TLSsecretsBackend_To_cilium_TLSsecretsBackend(&in.TLSsecretsBackend, &out.TLSsecretsBackend, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_WellKnownIdentities_To_cilium_WellKnownIdentities(&in.WellKnownIdentities, &out.WellKnownIdentities, s); err != nil {
		return err
	}
	out.CNI = (*cilium.CNI)(unsafe.Pointer(in.CNI))
	if err := Convert_v1alpha1_Psp_To_cilium_Psp(&in.Psp, &out.Psp, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_Agent_To_cilium_Agent(&in.Agent, &out.Agent, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ConfigEnable_To_cilium_ConfigEnable(&in.ConfigEnable, &out.ConfigEnable, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_XTSocketFallback_To_cilium_XTSocketFallback(&in.XTSocketFallback, &out.XTSocketFallback, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_K8SIPv4PodCIDR_To_cilium_K8SIPv4PodCIDR(&in.K8SIPv4PodCIDR, &out.K8SIPv4PodCIDR, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PolicyAuditMode_To_cilium_PolicyAuditMode(&in.PolicyAuditMode, &out.PolicyAuditMode, s); err != nil {
		return err
	}
	out.DaemonRunPath = (*cilium.DaemonRunPath)(unsafe.Pointer(in.DaemonRunPath))
	if err := Convert_v1alpha1_Eni_To_cilium_Eni(&in.Eni, &out.Eni, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_EndpointRoutes_To_cilium_EndpointRoutes(&in.EndpointRoutes, &out.EndpointRoutes, s); err != nil {
		return err
	}
	out.Azure = (*cilium.Azure)(unsafe.Pointer(in.Azure))
	out.OperatorPrometheus = (*cilium.OperatorPrometheus)(unsafe.Pointer(in.OperatorPrometheus))
	out.KubeProxy = (*cilium.KubeProxy)(unsafe.Pointer(in.KubeProxy))
	out.KubeProxyReplacementMode = (*cilium.KubeProxyReplacementMode)(unsafe.Pointer(in.KubeProxyReplacementMode))
	if err := Convert_v1alpha1_EtcdConfig_To_cilium_EtcdConfig(&in.EtcdConfig, &out.EtcdConfig, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_Masquerade_To_cilium_Masquerade(&in.Masquerade, &out.Masquerade, s); err != nil {
		return err
	}
	out.IPvlan = (*cilium.IPvlan)(unsafe.Pointer(in.IPvlan))
	out.Flannel = (*cilium.Flannel)(unsafe.Pointer(in.Flannel))
	out.AutoDirectNodeRoutes = (*cilium.AutoDirectNodeRoutes)(unsafe.Pointer(in.AutoDirectNodeRoutes))
	out.Encryption = (*cilium.Encryption)(unsafe.Pointer(in.Encryption))
	out.Hubble = (*cilium.Hubble)(unsafe.Pointer(in.Hubble))
	out.Nodeport = (*cilium.Nodeport)(unsafe.Pointer(in.Nodeport))
	if err := Convert_v1alpha1_IPv4_To_cilium_IPv4(&in.IPv4, &out.IPv4, s); err != nil {
		return err
	}
	out.IPv6 = (*cilium.IPv6)(unsafe.Pointer(in.IPv6))
	out.ExternalIP = (*cilium.ExternalIP)(unsafe.Pointer(in.ExternalIP))
	out.IPAMOptionMode = (*cilium.IPAMOptionMode)(unsafe.Pointer(in.IPAMOptionMode))
	out.IdentityAllocationModeOption = cilium.IdentityAllocationModeOption(in.IdentityAllocationModeOption)
	out.TunnelMode = cilium.TunnelMode(in.TunnelMode)
	return nil
}

// Convert_v1alpha1_NetworkConfig_To_cilium_NetworkConfig is an autogenerated conversion function.
func Convert_v1alpha1_NetworkConfig_To_cilium_NetworkConfig(in *NetworkConfig, out *cilium.NetworkConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkConfig_To_cilium_NetworkConfig(in, out, s)
}

func autoConvert_cilium_NetworkConfig_To_v1alpha1_NetworkConfig(in *cilium.NetworkConfig, out *NetworkConfig, s conversion.Scope) error {
	out.Debug = (*Debug)(unsafe.Pointer(in.Debug))
	if err := Convert_cilium_GoogleGKE_To_v1alpha1_GoogleGKE(&in.GoogleGKE, &out.GoogleGKE, s); err != nil {
		return err
	}
	if err := Convert_cilium_NodeInit_To_v1alpha1_NodeInit(&in.NodeInit, &out.NodeInit, s); err != nil {
		return err
	}
	out.Operator = (*Operator)(unsafe.Pointer(in.Operator))
	out.ClusterName = (*ClusterName)(unsafe.Pointer(in.ClusterName))
	out.Preflight = (*Preflight)(unsafe.Pointer(in.Preflight))
	out.CleanState = (*CleanState)(unsafe.Pointer(in.CleanState))
	out.CleanBpfState = (*CleanBpfState)(unsafe.Pointer(in.CleanBpfState))
	out.Bpf = (*Bpf)(unsafe.Pointer(in.Bpf))
	out.HostServices = (*HostServices)(unsafe.Pointer(in.HostServices))
	out.SockOps = (*SockOps)(unsafe.Pointer(in.SockOps))
	out.InstallIPTableRules = (*InstallIPTableRules)(unsafe.Pointer(in.InstallIPTableRules))
	out.Prometheus = (*Prometheus)(unsafe.Pointer(in.Prometheus))
	if err := Convert_cilium_SynchronizeK8sNodes_To_v1alpha1_SynchronizeK8sNodes(&in.SynchronizeK8sNodes, &out.SynchronizeK8sNodes, s); err != nil {
		return err
	}
	if err := Convert_cilium_RemoteNodeIdentity_To_v1alpha1_RemoteNodeIdentity(&in.RemoteNodeIdentity, &out.RemoteNodeIdentity, s); err != nil {
		return err
	}
	if err := Convert_cilium_TLSsecretsBackend_To_v1alpha1_TLSsecretsBackend(&in.TLSsecretsBackend, &out.TLSsecretsBackend, s); err != nil {
		return err
	}
	if err := Convert_cilium_WellKnownIdentities_To_v1alpha1_WellKnownIdentities(&in.WellKnownIdentities, &out.WellKnownIdentities, s); err != nil {
		return err
	}
	out.CNI = (*CNI)(unsafe.Pointer(in.CNI))
	if err := Convert_cilium_Psp_To_v1alpha1_Psp(&in.Psp, &out.Psp, s); err != nil {
		return err
	}
	if err := Convert_cilium_Agent_To_v1alpha1_Agent(&in.Agent, &out.Agent, s); err != nil {
		return err
	}
	if err := Convert_cilium_ConfigEnable_To_v1alpha1_ConfigEnable(&in.ConfigEnable, &out.ConfigEnable, s); err != nil {
		return err
	}
	if err := Convert_cilium_XTSocketFallback_To_v1alpha1_XTSocketFallback(&in.XTSocketFallback, &out.XTSocketFallback, s); err != nil {
		return err
	}
	if err := Convert_cilium_K8SIPv4PodCIDR_To_v1alpha1_K8SIPv4PodCIDR(&in.K8SIPv4PodCIDR, &out.K8SIPv4PodCIDR, s); err != nil {
		return err
	}
	if err := Convert_cilium_PolicyAuditMode_To_v1alpha1_PolicyAuditMode(&in.PolicyAuditMode, &out.PolicyAuditMode, s); err != nil {
		return err
	}
	out.DaemonRunPath = (*DaemonRunPath)(unsafe.Pointer(in.DaemonRunPath))
	if err := Convert_cilium_Eni_To_v1alpha1_Eni(&in.Eni, &out.Eni, s); err != nil {
		return err
	}
	if err := Convert_cilium_EndpointRoutes_To_v1alpha1_EndpointRoutes(&in.EndpointRoutes, &out.EndpointRoutes, s); err != nil {
		return err
	}
	out.Azure = (*Azure)(unsafe.Pointer(in.Azure))
	out.OperatorPrometheus = (*OperatorPrometheus)(unsafe.Pointer(in.OperatorPrometheus))
	out.KubeProxy = (*KubeProxy)(unsafe.Pointer(in.KubeProxy))
	out.KubeProxyReplacementMode = (*KubeProxyReplacementMode)(unsafe.Pointer(in.KubeProxyReplacementMode))
	if err := Convert_cilium_EtcdConfig_To_v1alpha1_EtcdConfig(&in.EtcdConfig, &out.EtcdConfig, s); err != nil {
		return err
	}
	if err := Convert_cilium_Masquerade_To_v1alpha1_Masquerade(&in.Masquerade, &out.Masquerade, s); err != nil {
		return err
	}
	out.IPvlan = (*IPvlan)(unsafe.Pointer(in.IPvlan))
	out.Flannel = (*Flannel)(unsafe.Pointer(in.Flannel))
	out.AutoDirectNodeRoutes = (*AutoDirectNodeRoutes)(unsafe.Pointer(in.AutoDirectNodeRoutes))
	out.Encryption = (*Encryption)(unsafe.Pointer(in.Encryption))
	out.Hubble = (*Hubble)(unsafe.Pointer(in.Hubble))
	out.Nodeport = (*Nodeport)(unsafe.Pointer(in.Nodeport))
	if err := Convert_cilium_IPv4_To_v1alpha1_IPv4(&in.IPv4, &out.IPv4, s); err != nil {
		return err
	}
	out.IPv6 = (*IPv6)(unsafe.Pointer(in.IPv6))
	out.ExternalIP = (*ExternalIP)(unsafe.Pointer(in.ExternalIP))
	out.IPAMOptionMode = (*IPAMOptionMode)(unsafe.Pointer(in.IPAMOptionMode))
	out.IdentityAllocationModeOption = IdentityAllocationModeOption(in.IdentityAllocationModeOption)
	out.TunnelMode = TunnelMode(in.TunnelMode)
	return nil
}

// Convert_cilium_NetworkConfig_To_v1alpha1_NetworkConfig is an autogenerated conversion function.
func Convert_cilium_NetworkConfig_To_v1alpha1_NetworkConfig(in *cilium.NetworkConfig, out *NetworkConfig, s conversion.Scope) error {
	return autoConvert_cilium_NetworkConfig_To_v1alpha1_NetworkConfig(in, out, s)
}

func autoConvert_v1alpha1_NetworkStatus_To_cilium_NetworkStatus(in *NetworkStatus, out *cilium.NetworkStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_NetworkStatus_To_cilium_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha1_NetworkStatus_To_cilium_NetworkStatus(in *NetworkStatus, out *cilium.NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkStatus_To_cilium_NetworkStatus(in, out, s)
}

func autoConvert_cilium_NetworkStatus_To_v1alpha1_NetworkStatus(in *cilium.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	return nil
}

// Convert_cilium_NetworkStatus_To_v1alpha1_NetworkStatus is an autogenerated conversion function.
func Convert_cilium_NetworkStatus_To_v1alpha1_NetworkStatus(in *cilium.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	return autoConvert_cilium_NetworkStatus_To_v1alpha1_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha1_NodeInit_To_cilium_NodeInit(in *NodeInit, out *cilium.NodeInit, s conversion.Scope) error {
	out.NodeInitEnabled = in.NodeInitEnabled
	out.BootStrapFile = in.BootStrapFile
	out.NonGlobalRestartPods = in.NonGlobalRestartPods
	out.NonGlobalReconfigureKubelet = in.NonGlobalReconfigureKubelet
	out.NonGlobalRemoveCbrBridge = in.NonGlobalRemoveCbrBridge
	out.NonGlobalRevertReconfigureKubelet = in.NonGlobalRevertReconfigureKubelet
	return nil
}

// Convert_v1alpha1_NodeInit_To_cilium_NodeInit is an autogenerated conversion function.
func Convert_v1alpha1_NodeInit_To_cilium_NodeInit(in *NodeInit, out *cilium.NodeInit, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeInit_To_cilium_NodeInit(in, out, s)
}

func autoConvert_cilium_NodeInit_To_v1alpha1_NodeInit(in *cilium.NodeInit, out *NodeInit, s conversion.Scope) error {
	out.NodeInitEnabled = in.NodeInitEnabled
	out.BootStrapFile = in.BootStrapFile
	out.NonGlobalRestartPods = in.NonGlobalRestartPods
	out.NonGlobalReconfigureKubelet = in.NonGlobalReconfigureKubelet
	out.NonGlobalRemoveCbrBridge = in.NonGlobalRemoveCbrBridge
	out.NonGlobalRevertReconfigureKubelet = in.NonGlobalRevertReconfigureKubelet
	return nil
}

// Convert_cilium_NodeInit_To_v1alpha1_NodeInit is an autogenerated conversion function.
func Convert_cilium_NodeInit_To_v1alpha1_NodeInit(in *cilium.NodeInit, out *NodeInit, s conversion.Scope) error {
	return autoConvert_cilium_NodeInit_To_v1alpha1_NodeInit(in, out, s)
}

func autoConvert_v1alpha1_Nodeport_To_cilium_Nodeport(in *Nodeport, out *cilium.Nodeport, s conversion.Scope) error {
	out.NodeportEnabled = in.NodeportEnabled
	out.NodeportMode = in.NodeportMode
	out.NodeportDevice = in.NodeportDevice
	out.NodeportRange = in.NodeportRange
	return nil
}

// Convert_v1alpha1_Nodeport_To_cilium_Nodeport is an autogenerated conversion function.
func Convert_v1alpha1_Nodeport_To_cilium_Nodeport(in *Nodeport, out *cilium.Nodeport, s conversion.Scope) error {
	return autoConvert_v1alpha1_Nodeport_To_cilium_Nodeport(in, out, s)
}

func autoConvert_cilium_Nodeport_To_v1alpha1_Nodeport(in *cilium.Nodeport, out *Nodeport, s conversion.Scope) error {
	out.NodeportEnabled = in.NodeportEnabled
	out.NodeportMode = in.NodeportMode
	out.NodeportDevice = in.NodeportDevice
	out.NodeportRange = in.NodeportRange
	return nil
}

// Convert_cilium_Nodeport_To_v1alpha1_Nodeport is an autogenerated conversion function.
func Convert_cilium_Nodeport_To_v1alpha1_Nodeport(in *cilium.Nodeport, out *Nodeport, s conversion.Scope) error {
	return autoConvert_cilium_Nodeport_To_v1alpha1_Nodeport(in, out, s)
}

func autoConvert_v1alpha1_Operator_To_cilium_Operator(in *Operator, out *cilium.Operator, s conversion.Scope) error {
	out.OperatorEnabled = in.OperatorEnabled
	return nil
}

// Convert_v1alpha1_Operator_To_cilium_Operator is an autogenerated conversion function.
func Convert_v1alpha1_Operator_To_cilium_Operator(in *Operator, out *cilium.Operator, s conversion.Scope) error {
	return autoConvert_v1alpha1_Operator_To_cilium_Operator(in, out, s)
}

func autoConvert_cilium_Operator_To_v1alpha1_Operator(in *cilium.Operator, out *Operator, s conversion.Scope) error {
	out.OperatorEnabled = in.OperatorEnabled
	return nil
}

// Convert_cilium_Operator_To_v1alpha1_Operator is an autogenerated conversion function.
func Convert_cilium_Operator_To_v1alpha1_Operator(in *cilium.Operator, out *Operator, s conversion.Scope) error {
	return autoConvert_cilium_Operator_To_v1alpha1_Operator(in, out, s)
}

func autoConvert_v1alpha1_OperatorPrometheus_To_cilium_OperatorPrometheus(in *OperatorPrometheus, out *cilium.OperatorPrometheus, s conversion.Scope) error {
	out.OperatorPrometheusEnabled = in.OperatorPrometheusEnabled
	out.Port = in.Port
	return nil
}

// Convert_v1alpha1_OperatorPrometheus_To_cilium_OperatorPrometheus is an autogenerated conversion function.
func Convert_v1alpha1_OperatorPrometheus_To_cilium_OperatorPrometheus(in *OperatorPrometheus, out *cilium.OperatorPrometheus, s conversion.Scope) error {
	return autoConvert_v1alpha1_OperatorPrometheus_To_cilium_OperatorPrometheus(in, out, s)
}

func autoConvert_cilium_OperatorPrometheus_To_v1alpha1_OperatorPrometheus(in *cilium.OperatorPrometheus, out *OperatorPrometheus, s conversion.Scope) error {
	out.OperatorPrometheusEnabled = in.OperatorPrometheusEnabled
	out.Port = in.Port
	return nil
}

// Convert_cilium_OperatorPrometheus_To_v1alpha1_OperatorPrometheus is an autogenerated conversion function.
func Convert_cilium_OperatorPrometheus_To_v1alpha1_OperatorPrometheus(in *cilium.OperatorPrometheus, out *OperatorPrometheus, s conversion.Scope) error {
	return autoConvert_cilium_OperatorPrometheus_To_v1alpha1_OperatorPrometheus(in, out, s)
}

func autoConvert_v1alpha1_PolicyAuditMode_To_cilium_PolicyAuditMode(in *PolicyAuditMode, out *cilium.PolicyAuditMode, s conversion.Scope) error {
	out.PolicyAuditModeEnabled = in.PolicyAuditModeEnabled
	return nil
}

// Convert_v1alpha1_PolicyAuditMode_To_cilium_PolicyAuditMode is an autogenerated conversion function.
func Convert_v1alpha1_PolicyAuditMode_To_cilium_PolicyAuditMode(in *PolicyAuditMode, out *cilium.PolicyAuditMode, s conversion.Scope) error {
	return autoConvert_v1alpha1_PolicyAuditMode_To_cilium_PolicyAuditMode(in, out, s)
}

func autoConvert_cilium_PolicyAuditMode_To_v1alpha1_PolicyAuditMode(in *cilium.PolicyAuditMode, out *PolicyAuditMode, s conversion.Scope) error {
	out.PolicyAuditModeEnabled = in.PolicyAuditModeEnabled
	return nil
}

// Convert_cilium_PolicyAuditMode_To_v1alpha1_PolicyAuditMode is an autogenerated conversion function.
func Convert_cilium_PolicyAuditMode_To_v1alpha1_PolicyAuditMode(in *cilium.PolicyAuditMode, out *PolicyAuditMode, s conversion.Scope) error {
	return autoConvert_cilium_PolicyAuditMode_To_v1alpha1_PolicyAuditMode(in, out, s)
}

func autoConvert_v1alpha1_Preflight_To_cilium_Preflight(in *Preflight, out *cilium.Preflight, s conversion.Scope) error {
	out.PreflightEnabled = in.PreflightEnabled
	out.PreCacheToFQDNS = in.PreCacheToFQDNS
	return nil
}

// Convert_v1alpha1_Preflight_To_cilium_Preflight is an autogenerated conversion function.
func Convert_v1alpha1_Preflight_To_cilium_Preflight(in *Preflight, out *cilium.Preflight, s conversion.Scope) error {
	return autoConvert_v1alpha1_Preflight_To_cilium_Preflight(in, out, s)
}

func autoConvert_cilium_Preflight_To_v1alpha1_Preflight(in *cilium.Preflight, out *Preflight, s conversion.Scope) error {
	out.PreflightEnabled = in.PreflightEnabled
	out.PreCacheToFQDNS = in.PreCacheToFQDNS
	return nil
}

// Convert_cilium_Preflight_To_v1alpha1_Preflight is an autogenerated conversion function.
func Convert_cilium_Preflight_To_v1alpha1_Preflight(in *cilium.Preflight, out *Preflight, s conversion.Scope) error {
	return autoConvert_cilium_Preflight_To_v1alpha1_Preflight(in, out, s)
}

func autoConvert_v1alpha1_Prometheus_To_cilium_Prometheus(in *Prometheus, out *cilium.Prometheus, s conversion.Scope) error {
	out.PrometheusEnabled = in.PrometheusEnabled
	out.Port = in.Port
	out.ServiceMonitorEnabled = in.ServiceMonitorEnabled
	return nil
}

// Convert_v1alpha1_Prometheus_To_cilium_Prometheus is an autogenerated conversion function.
func Convert_v1alpha1_Prometheus_To_cilium_Prometheus(in *Prometheus, out *cilium.Prometheus, s conversion.Scope) error {
	return autoConvert_v1alpha1_Prometheus_To_cilium_Prometheus(in, out, s)
}

func autoConvert_cilium_Prometheus_To_v1alpha1_Prometheus(in *cilium.Prometheus, out *Prometheus, s conversion.Scope) error {
	out.PrometheusEnabled = in.PrometheusEnabled
	out.Port = in.Port
	out.ServiceMonitorEnabled = in.ServiceMonitorEnabled
	return nil
}

// Convert_cilium_Prometheus_To_v1alpha1_Prometheus is an autogenerated conversion function.
func Convert_cilium_Prometheus_To_v1alpha1_Prometheus(in *cilium.Prometheus, out *Prometheus, s conversion.Scope) error {
	return autoConvert_cilium_Prometheus_To_v1alpha1_Prometheus(in, out, s)
}

func autoConvert_v1alpha1_Psp_To_cilium_Psp(in *Psp, out *cilium.Psp, s conversion.Scope) error {
	out.PspEnabled = in.PspEnabled
	return nil
}

// Convert_v1alpha1_Psp_To_cilium_Psp is an autogenerated conversion function.
func Convert_v1alpha1_Psp_To_cilium_Psp(in *Psp, out *cilium.Psp, s conversion.Scope) error {
	return autoConvert_v1alpha1_Psp_To_cilium_Psp(in, out, s)
}

func autoConvert_cilium_Psp_To_v1alpha1_Psp(in *cilium.Psp, out *Psp, s conversion.Scope) error {
	out.PspEnabled = in.PspEnabled
	return nil
}

// Convert_cilium_Psp_To_v1alpha1_Psp is an autogenerated conversion function.
func Convert_cilium_Psp_To_v1alpha1_Psp(in *cilium.Psp, out *Psp, s conversion.Scope) error {
	return autoConvert_cilium_Psp_To_v1alpha1_Psp(in, out, s)
}

func autoConvert_v1alpha1_RemoteNodeIdentity_To_cilium_RemoteNodeIdentity(in *RemoteNodeIdentity, out *cilium.RemoteNodeIdentity, s conversion.Scope) error {
	out.RemoteNodeIdentityEnabled = in.RemoteNodeIdentityEnabled
	return nil
}

// Convert_v1alpha1_RemoteNodeIdentity_To_cilium_RemoteNodeIdentity is an autogenerated conversion function.
func Convert_v1alpha1_RemoteNodeIdentity_To_cilium_RemoteNodeIdentity(in *RemoteNodeIdentity, out *cilium.RemoteNodeIdentity, s conversion.Scope) error {
	return autoConvert_v1alpha1_RemoteNodeIdentity_To_cilium_RemoteNodeIdentity(in, out, s)
}

func autoConvert_cilium_RemoteNodeIdentity_To_v1alpha1_RemoteNodeIdentity(in *cilium.RemoteNodeIdentity, out *RemoteNodeIdentity, s conversion.Scope) error {
	out.RemoteNodeIdentityEnabled = in.RemoteNodeIdentityEnabled
	return nil
}

// Convert_cilium_RemoteNodeIdentity_To_v1alpha1_RemoteNodeIdentity is an autogenerated conversion function.
func Convert_cilium_RemoteNodeIdentity_To_v1alpha1_RemoteNodeIdentity(in *cilium.RemoteNodeIdentity, out *RemoteNodeIdentity, s conversion.Scope) error {
	return autoConvert_cilium_RemoteNodeIdentity_To_v1alpha1_RemoteNodeIdentity(in, out, s)
}

func autoConvert_v1alpha1_SockOps_To_cilium_SockOps(in *SockOps, out *cilium.SockOps, s conversion.Scope) error {
	out.SockOpsEnabled = in.SockOpsEnabled
	return nil
}

// Convert_v1alpha1_SockOps_To_cilium_SockOps is an autogenerated conversion function.
func Convert_v1alpha1_SockOps_To_cilium_SockOps(in *SockOps, out *cilium.SockOps, s conversion.Scope) error {
	return autoConvert_v1alpha1_SockOps_To_cilium_SockOps(in, out, s)
}

func autoConvert_cilium_SockOps_To_v1alpha1_SockOps(in *cilium.SockOps, out *SockOps, s conversion.Scope) error {
	out.SockOpsEnabled = in.SockOpsEnabled
	return nil
}

// Convert_cilium_SockOps_To_v1alpha1_SockOps is an autogenerated conversion function.
func Convert_cilium_SockOps_To_v1alpha1_SockOps(in *cilium.SockOps, out *SockOps, s conversion.Scope) error {
	return autoConvert_cilium_SockOps_To_v1alpha1_SockOps(in, out, s)
}

func autoConvert_v1alpha1_SynchronizeK8sNodes_To_cilium_SynchronizeK8sNodes(in *SynchronizeK8sNodes, out *cilium.SynchronizeK8sNodes, s conversion.Scope) error {
	out.SynchronizeK8sNodesEnabled = in.SynchronizeK8sNodesEnabled
	return nil
}

// Convert_v1alpha1_SynchronizeK8sNodes_To_cilium_SynchronizeK8sNodes is an autogenerated conversion function.
func Convert_v1alpha1_SynchronizeK8sNodes_To_cilium_SynchronizeK8sNodes(in *SynchronizeK8sNodes, out *cilium.SynchronizeK8sNodes, s conversion.Scope) error {
	return autoConvert_v1alpha1_SynchronizeK8sNodes_To_cilium_SynchronizeK8sNodes(in, out, s)
}

func autoConvert_cilium_SynchronizeK8sNodes_To_v1alpha1_SynchronizeK8sNodes(in *cilium.SynchronizeK8sNodes, out *SynchronizeK8sNodes, s conversion.Scope) error {
	out.SynchronizeK8sNodesEnabled = in.SynchronizeK8sNodesEnabled
	return nil
}

// Convert_cilium_SynchronizeK8sNodes_To_v1alpha1_SynchronizeK8sNodes is an autogenerated conversion function.
func Convert_cilium_SynchronizeK8sNodes_To_v1alpha1_SynchronizeK8sNodes(in *cilium.SynchronizeK8sNodes, out *SynchronizeK8sNodes, s conversion.Scope) error {
	return autoConvert_cilium_SynchronizeK8sNodes_To_v1alpha1_SynchronizeK8sNodes(in, out, s)
}

func autoConvert_v1alpha1_TLSsecretsBackend_To_cilium_TLSsecretsBackend(in *TLSsecretsBackend, out *cilium.TLSsecretsBackend, s conversion.Scope) error {
	out.TLSsecretsBackend = in.TLSsecretsBackend
	return nil
}

// Convert_v1alpha1_TLSsecretsBackend_To_cilium_TLSsecretsBackend is an autogenerated conversion function.
func Convert_v1alpha1_TLSsecretsBackend_To_cilium_TLSsecretsBackend(in *TLSsecretsBackend, out *cilium.TLSsecretsBackend, s conversion.Scope) error {
	return autoConvert_v1alpha1_TLSsecretsBackend_To_cilium_TLSsecretsBackend(in, out, s)
}

func autoConvert_cilium_TLSsecretsBackend_To_v1alpha1_TLSsecretsBackend(in *cilium.TLSsecretsBackend, out *TLSsecretsBackend, s conversion.Scope) error {
	out.TLSsecretsBackend = in.TLSsecretsBackend
	return nil
}

// Convert_cilium_TLSsecretsBackend_To_v1alpha1_TLSsecretsBackend is an autogenerated conversion function.
func Convert_cilium_TLSsecretsBackend_To_v1alpha1_TLSsecretsBackend(in *cilium.TLSsecretsBackend, out *TLSsecretsBackend, s conversion.Scope) error {
	return autoConvert_cilium_TLSsecretsBackend_To_v1alpha1_TLSsecretsBackend(in, out, s)
}

func autoConvert_v1alpha1_WellKnownIdentities_To_cilium_WellKnownIdentities(in *WellKnownIdentities, out *cilium.WellKnownIdentities, s conversion.Scope) error {
	out.WellKnownIdentitiesEnabled = in.WellKnownIdentitiesEnabled
	return nil
}

// Convert_v1alpha1_WellKnownIdentities_To_cilium_WellKnownIdentities is an autogenerated conversion function.
func Convert_v1alpha1_WellKnownIdentities_To_cilium_WellKnownIdentities(in *WellKnownIdentities, out *cilium.WellKnownIdentities, s conversion.Scope) error {
	return autoConvert_v1alpha1_WellKnownIdentities_To_cilium_WellKnownIdentities(in, out, s)
}

func autoConvert_cilium_WellKnownIdentities_To_v1alpha1_WellKnownIdentities(in *cilium.WellKnownIdentities, out *WellKnownIdentities, s conversion.Scope) error {
	out.WellKnownIdentitiesEnabled = in.WellKnownIdentitiesEnabled
	return nil
}

// Convert_cilium_WellKnownIdentities_To_v1alpha1_WellKnownIdentities is an autogenerated conversion function.
func Convert_cilium_WellKnownIdentities_To_v1alpha1_WellKnownIdentities(in *cilium.WellKnownIdentities, out *WellKnownIdentities, s conversion.Scope) error {
	return autoConvert_cilium_WellKnownIdentities_To_v1alpha1_WellKnownIdentities(in, out, s)
}

func autoConvert_v1alpha1_XTSocketFallback_To_cilium_XTSocketFallback(in *XTSocketFallback, out *cilium.XTSocketFallback, s conversion.Scope) error {
	out.XTSocketFallbackEnabled = in.XTSocketFallbackEnabled
	return nil
}

// Convert_v1alpha1_XTSocketFallback_To_cilium_XTSocketFallback is an autogenerated conversion function.
func Convert_v1alpha1_XTSocketFallback_To_cilium_XTSocketFallback(in *XTSocketFallback, out *cilium.XTSocketFallback, s conversion.Scope) error {
	return autoConvert_v1alpha1_XTSocketFallback_To_cilium_XTSocketFallback(in, out, s)
}

func autoConvert_cilium_XTSocketFallback_To_v1alpha1_XTSocketFallback(in *cilium.XTSocketFallback, out *XTSocketFallback, s conversion.Scope) error {
	out.XTSocketFallbackEnabled = in.XTSocketFallbackEnabled
	return nil
}

// Convert_cilium_XTSocketFallback_To_v1alpha1_XTSocketFallback is an autogenerated conversion function.
func Convert_cilium_XTSocketFallback_To_v1alpha1_XTSocketFallback(in *cilium.XTSocketFallback, out *XTSocketFallback, s conversion.Scope) error {
	return autoConvert_cilium_XTSocketFallback_To_v1alpha1_XTSocketFallback(in, out, s)
}
