apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-etcd-operator
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.useProjectedTokenMount }}
automountServiceAccountToken: false
{{- end }}
