{{- if .Values.global.psp.enabled }}
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.hubble-relay
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: RunAsAny
  hostPorts:
  - max: 0
    min: 0
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - projected
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:hubble-relay
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - gardener.kube-system.hubble-relay
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener.cloud:psp:kube-system:hubble-relay
roleRef:
  kind: ClusterRole
  name: gardener.cloud:psp:kube-system:hubble-relay
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: hubble-relay
  namespace: {{ .Release.Namespace }}
---
# hubble-generate-certs
apiVersion: {{ include "podsecuritypolicyversion" .}}
kind: PodSecurityPolicy
metadata:
  name: gardener.kube-system.hubble-generate-certs
spec:
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener.cloud:psp:kube-system:hubble-generate-certs
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - gardener.kube-system.hubble-generate-certs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gardener.cloud:psp:kube-system:hubble-generate-certs
roleRef:
  kind: ClusterRole
  name: gardener.cloud:psp:kube-system:hubble-generate-certs
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: hubble-generate-certs
  namespace: {{ .Release.Namespace }}
{{- end }}
