apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Chart.Name }}
spec:
  type: "ClusterIP"
  selector:
    k8s-app: {{ .Chart.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.listenPort }}
