---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble-relay
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.useProjectedTokenMount }}
automountServiceAccountToken: false
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble-generate-certs
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.useProjectedTokenMount }}
automountServiceAccountToken: false
{{- end }}
