---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble-relay
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble-generate-certs
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
