{{- if .Values.global.gatewayAPI.enabled }}
# Source: cilium/templates/cilium-secrets-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.gatewayAPI.secretsNamespace | quote }}
  labels:
    app.kubernetes.io/part-of: cilium
{{- end }}
