# Source: https://docs.cilium.io/en/stable/operations/performance/scalability/identity-relevant-labels/#identity-relevant-labels
apiVersion: v1
kind: ConfigMap
metadata:
  name: label-prefix-conf
  namespace: {{ .Release.Namespace }}
immutable: true
data:
  label-prefix: |
    {
    "version": 1,
    "valid-prefixes": [
        {
            "prefix": "io.kubernetes",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "kubernetes.io",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "apps.kubernetes.io/pod-index",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "batch.kubernetes.io/job-completion-index",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "batch.kubernetes.io/controller-uid",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "beta.kubernetes.io",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "k8s.io",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "pod-template-generation",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "pod-template-hash",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "controller-revision-hash",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "annotation.*",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "controller-uid",
            "source": "any",
            "invert": true
        },
        {
            "prefix": "etcd_node",
            "source": "any",
            "invert": true
        }
    ]
    }
