# Source: cilium/templates/cilium-envoy/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-envoy-config
  namespace: {{ .Release.Namespace }}
data:
  # Keep the key name as bootstrap-config.json to avoid breaking changes
  bootstrap-config.json: |
    {{- (tpl (.Files.Get "files/bootstrap-config.yaml") .) | fromYaml | toJson | nindent 4 }}
    
