{{- if .Values.global.vpa.enabled}}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "name" . }}-vpa
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.global.vpa.resourcePolicy }}
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      {{- if .Values.global.vpa.resourcePolicy.minAllowed }}
      minAllowed:
        memory: {{ required ".Values.global.vpa.resourcePolicy.minAllowed.memory is required" .Values.global.vpa.resourcePolicy.minAllowed.memory }}
      {{- end }}
      {{- if .Values.global.vpa.resourcePolicy.maxAllowed }}
      maxAllowed:
        cpu: {{ required ".Values.global.vpa.resourcePolicy.maxAllowed.cpu is required" .Values.global.vpa.resourcePolicy.maxAllowed.cpu }}
        memory: {{ required ".Values.global.vpa.resourcePolicy.maxAllowed.memory is required" .Values.global.vpa.resourcePolicy.maxAllowed.memory }}
      {{- end }}
  {{- end }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "name" . }}
  updatePolicy:
    updateMode: {{ .Values.global.vpa.updatePolicy.updateMode }}
{{- end }}
