apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.encryption.secretName | quote }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.global.encryption.keyFile }}: {{ printf "%s %s %s %s" .Values.global.encryption.ipsec.keyId .Values.global.encryption.ipsec.encryptionAlgorithms (.Values.global.encryption.ipsec.preSharedKey | default (randAlphaNum 32 | sha256sum)) (.Values.global.encryption.ipsec.keySize | toJson) | b64enc | quote }}
