// +build !ignore_autogenerated

/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package cilium

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoDirectNodeRoutes) DeepCopyInto(out *AutoDirectNodeRoutes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoDirectNodeRoutes.
func (in *AutoDirectNodeRoutes) DeepCopy() *AutoDirectNodeRoutes {
	if in == nil {
		return nil
	}
	out := new(AutoDirectNodeRoutes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Azure) DeepCopyInto(out *Azure) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Azure.
func (in *Azure) DeepCopy() *Azure {
	if in == nil {
		return nil
	}
	out := new(Azure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Bpf) DeepCopyInto(out *Bpf) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Bpf.
func (in *Bpf) DeepCopy() *Bpf {
	if in == nil {
		return nil
	}
	out := new(Bpf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNI) DeepCopyInto(out *CNI) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNI.
func (in *CNI) DeepCopy() *CNI {
	if in == nil {
		return nil
	}
	out := new(CNI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanBpfState) DeepCopyInto(out *CleanBpfState) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanBpfState.
func (in *CleanBpfState) DeepCopy() *CleanBpfState {
	if in == nil {
		return nil
	}
	out := new(CleanBpfState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanState) DeepCopyInto(out *CleanState) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanState.
func (in *CleanState) DeepCopy() *CleanState {
	if in == nil {
		return nil
	}
	out := new(CleanState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterName) DeepCopyInto(out *ClusterName) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterName.
func (in *ClusterName) DeepCopy() *ClusterName {
	if in == nil {
		return nil
	}
	out := new(ClusterName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigEnable) DeepCopyInto(out *ConfigEnable) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigEnable.
func (in *ConfigEnable) DeepCopy() *ConfigEnable {
	if in == nil {
		return nil
	}
	out := new(ConfigEnable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaemonRunPath) DeepCopyInto(out *DaemonRunPath) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaemonRunPath.
func (in *DaemonRunPath) DeepCopy() *DaemonRunPath {
	if in == nil {
		return nil
	}
	out := new(DaemonRunPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Debug) DeepCopyInto(out *Debug) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Debug.
func (in *Debug) DeepCopy() *Debug {
	if in == nil {
		return nil
	}
	out := new(Debug)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Encryption) DeepCopyInto(out *Encryption) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Encryption.
func (in *Encryption) DeepCopy() *Encryption {
	if in == nil {
		return nil
	}
	out := new(Encryption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointRoutes) DeepCopyInto(out *EndpointRoutes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointRoutes.
func (in *EndpointRoutes) DeepCopy() *EndpointRoutes {
	if in == nil {
		return nil
	}
	out := new(EndpointRoutes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Eni) DeepCopyInto(out *Eni) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Eni.
func (in *Eni) DeepCopy() *Eni {
	if in == nil {
		return nil
	}
	out := new(Eni)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdConfig) DeepCopyInto(out *EtcdConfig) {
	*out = *in
	if in.EtcdEndpoints != nil {
		in, out := &in.EtcdEndpoints, &out.EtcdEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdConfig.
func (in *EtcdConfig) DeepCopy() *EtcdConfig {
	if in == nil {
		return nil
	}
	out := new(EtcdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalIP) DeepCopyInto(out *ExternalIP) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalIP.
func (in *ExternalIP) DeepCopy() *ExternalIP {
	if in == nil {
		return nil
	}
	out := new(ExternalIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Flannel) DeepCopyInto(out *Flannel) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Flannel.
func (in *Flannel) DeepCopy() *Flannel {
	if in == nil {
		return nil
	}
	out := new(Flannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleGKE) DeepCopyInto(out *GoogleGKE) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleGKE.
func (in *GoogleGKE) DeepCopy() *GoogleGKE {
	if in == nil {
		return nil
	}
	out := new(GoogleGKE)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostServices) DeepCopyInto(out *HostServices) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostServices.
func (in *HostServices) DeepCopy() *HostServices {
	if in == nil {
		return nil
	}
	out := new(HostServices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hubble) DeepCopyInto(out *Hubble) {
	*out = *in
	if in.ListenAddresses != nil {
		in, out := &in.ListenAddresses, &out.ListenAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hubble.
func (in *Hubble) DeepCopy() *Hubble {
	if in == nil {
		return nil
	}
	out := new(Hubble)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv4) DeepCopyInto(out *IPv4) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv4.
func (in *IPv4) DeepCopy() *IPv4 {
	if in == nil {
		return nil
	}
	out := new(IPv4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPv6) DeepCopyInto(out *IPv6) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPv6.
func (in *IPv6) DeepCopy() *IPv6 {
	if in == nil {
		return nil
	}
	out := new(IPv6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPvlan) DeepCopyInto(out *IPvlan) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPvlan.
func (in *IPvlan) DeepCopy() *IPvlan {
	if in == nil {
		return nil
	}
	out := new(IPvlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallIPTableRules) DeepCopyInto(out *InstallIPTableRules) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallIPTableRules.
func (in *InstallIPTableRules) DeepCopy() *InstallIPTableRules {
	if in == nil {
		return nil
	}
	out := new(InstallIPTableRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8SIPv4PodCIDR) DeepCopyInto(out *K8SIPv4PodCIDR) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8SIPv4PodCIDR.
func (in *K8SIPv4PodCIDR) DeepCopy() *K8SIPv4PodCIDR {
	if in == nil {
		return nil
	}
	out := new(K8SIPv4PodCIDR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeProxy) DeepCopyInto(out *KubeProxy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeProxy.
func (in *KubeProxy) DeepCopy() *KubeProxy {
	if in == nil {
		return nil
	}
	out := new(KubeProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Masquerade) DeepCopyInto(out *Masquerade) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Masquerade.
func (in *Masquerade) DeepCopy() *Masquerade {
	if in == nil {
		return nil
	}
	out := new(Masquerade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfig) DeepCopyInto(out *NetworkConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(Debug)
		**out = **in
	}
	out.GoogleGKE = in.GoogleGKE
	out.NodeInit = in.NodeInit
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(Operator)
		**out = **in
	}
	if in.ClusterName != nil {
		in, out := &in.ClusterName, &out.ClusterName
		*out = new(ClusterName)
		**out = **in
	}
	if in.Preflight != nil {
		in, out := &in.Preflight, &out.Preflight
		*out = new(Preflight)
		**out = **in
	}
	if in.CleanState != nil {
		in, out := &in.CleanState, &out.CleanState
		*out = new(CleanState)
		**out = **in
	}
	if in.CleanBpfState != nil {
		in, out := &in.CleanBpfState, &out.CleanBpfState
		*out = new(CleanBpfState)
		**out = **in
	}
	if in.Bpf != nil {
		in, out := &in.Bpf, &out.Bpf
		*out = new(Bpf)
		**out = **in
	}
	if in.HostServices != nil {
		in, out := &in.HostServices, &out.HostServices
		*out = new(HostServices)
		**out = **in
	}
	if in.SockOps != nil {
		in, out := &in.SockOps, &out.SockOps
		*out = new(SockOps)
		**out = **in
	}
	if in.InstallIPTableRules != nil {
		in, out := &in.InstallIPTableRules, &out.InstallIPTableRules
		*out = new(InstallIPTableRules)
		**out = **in
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(Prometheus)
		**out = **in
	}
	out.SynchronizeK8sNodes = in.SynchronizeK8sNodes
	out.RemoteNodeIdentity = in.RemoteNodeIdentity
	out.TLSsecretsBackend = in.TLSsecretsBackend
	out.WellKnownIdentities = in.WellKnownIdentities
	if in.CNI != nil {
		in, out := &in.CNI, &out.CNI
		*out = new(CNI)
		**out = **in
	}
	out.Psp = in.Psp
	out.Agent = in.Agent
	out.ConfigEnable = in.ConfigEnable
	out.XTSocketFallback = in.XTSocketFallback
	out.K8SIPv4PodCIDR = in.K8SIPv4PodCIDR
	out.PolicyAuditMode = in.PolicyAuditMode
	if in.DaemonRunPath != nil {
		in, out := &in.DaemonRunPath, &out.DaemonRunPath
		*out = new(DaemonRunPath)
		**out = **in
	}
	out.Eni = in.Eni
	out.EndpointRoutes = in.EndpointRoutes
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(Azure)
		**out = **in
	}
	if in.OperatorPrometheus != nil {
		in, out := &in.OperatorPrometheus, &out.OperatorPrometheus
		*out = new(OperatorPrometheus)
		**out = **in
	}
	if in.KubeProxy != nil {
		in, out := &in.KubeProxy, &out.KubeProxy
		*out = new(KubeProxy)
		**out = **in
	}
	if in.KubeProxyReplacementMode != nil {
		in, out := &in.KubeProxyReplacementMode, &out.KubeProxyReplacementMode
		*out = new(KubeProxyReplacementMode)
		**out = **in
	}
	in.EtcdConfig.DeepCopyInto(&out.EtcdConfig)
	out.Masquerade = in.Masquerade
	if in.IPvlan != nil {
		in, out := &in.IPvlan, &out.IPvlan
		*out = new(IPvlan)
		**out = **in
	}
	if in.Flannel != nil {
		in, out := &in.Flannel, &out.Flannel
		*out = new(Flannel)
		**out = **in
	}
	if in.AutoDirectNodeRoutes != nil {
		in, out := &in.AutoDirectNodeRoutes, &out.AutoDirectNodeRoutes
		*out = new(AutoDirectNodeRoutes)
		**out = **in
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(Encryption)
		**out = **in
	}
	if in.Hubble != nil {
		in, out := &in.Hubble, &out.Hubble
		*out = new(Hubble)
		(*in).DeepCopyInto(*out)
	}
	if in.Nodeport != nil {
		in, out := &in.Nodeport, &out.Nodeport
		*out = new(Nodeport)
		**out = **in
	}
	out.IPv4 = in.IPv4
	if in.IPv6 != nil {
		in, out := &in.IPv6, &out.IPv6
		*out = new(IPv6)
		**out = **in
	}
	if in.ExternalIP != nil {
		in, out := &in.ExternalIP, &out.ExternalIP
		*out = new(ExternalIP)
		**out = **in
	}
	if in.IPAMOptionMode != nil {
		in, out := &in.IPAMOptionMode, &out.IPAMOptionMode
		*out = new(IPAMOptionMode)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfig.
func (in *NetworkConfig) DeepCopy() *NetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInit) DeepCopyInto(out *NodeInit) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInit.
func (in *NodeInit) DeepCopy() *NodeInit {
	if in == nil {
		return nil
	}
	out := new(NodeInit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nodeport) DeepCopyInto(out *Nodeport) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nodeport.
func (in *Nodeport) DeepCopy() *Nodeport {
	if in == nil {
		return nil
	}
	out := new(Nodeport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Operator) DeepCopyInto(out *Operator) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Operator.
func (in *Operator) DeepCopy() *Operator {
	if in == nil {
		return nil
	}
	out := new(Operator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorPrometheus) DeepCopyInto(out *OperatorPrometheus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorPrometheus.
func (in *OperatorPrometheus) DeepCopy() *OperatorPrometheus {
	if in == nil {
		return nil
	}
	out := new(OperatorPrometheus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAuditMode) DeepCopyInto(out *PolicyAuditMode) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAuditMode.
func (in *PolicyAuditMode) DeepCopy() *PolicyAuditMode {
	if in == nil {
		return nil
	}
	out := new(PolicyAuditMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Preflight) DeepCopyInto(out *Preflight) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Preflight.
func (in *Preflight) DeepCopy() *Preflight {
	if in == nil {
		return nil
	}
	out := new(Preflight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Prometheus) DeepCopyInto(out *Prometheus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Prometheus.
func (in *Prometheus) DeepCopy() *Prometheus {
	if in == nil {
		return nil
	}
	out := new(Prometheus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Psp) DeepCopyInto(out *Psp) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Psp.
func (in *Psp) DeepCopy() *Psp {
	if in == nil {
		return nil
	}
	out := new(Psp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteNodeIdentity) DeepCopyInto(out *RemoteNodeIdentity) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteNodeIdentity.
func (in *RemoteNodeIdentity) DeepCopy() *RemoteNodeIdentity {
	if in == nil {
		return nil
	}
	out := new(RemoteNodeIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SockOps) DeepCopyInto(out *SockOps) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SockOps.
func (in *SockOps) DeepCopy() *SockOps {
	if in == nil {
		return nil
	}
	out := new(SockOps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynchronizeK8sNodes) DeepCopyInto(out *SynchronizeK8sNodes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynchronizeK8sNodes.
func (in *SynchronizeK8sNodes) DeepCopy() *SynchronizeK8sNodes {
	if in == nil {
		return nil
	}
	out := new(SynchronizeK8sNodes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSsecretsBackend) DeepCopyInto(out *TLSsecretsBackend) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSsecretsBackend.
func (in *TLSsecretsBackend) DeepCopy() *TLSsecretsBackend {
	if in == nil {
		return nil
	}
	out := new(TLSsecretsBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WellKnownIdentities) DeepCopyInto(out *WellKnownIdentities) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WellKnownIdentities.
func (in *WellKnownIdentities) DeepCopy() *WellKnownIdentities {
	if in == nil {
		return nil
	}
	out := new(WellKnownIdentities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XTSocketFallback) DeepCopyInto(out *XTSocketFallback) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XTSocketFallback.
func (in *XTSocketFallback) DeepCopy() *XTSocketFallback {
	if in == nil {
		return nil
	}
	out := new(XTSocketFallback)
	in.DeepCopyInto(out)
	return out
}
